(() => {
 const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,tagline=document.querySelector('.dashboard-hero p');
 function greeting(){let hour=new Date().getHours();try{const zone=JSON.parse(localStorage.getItem('sg-timezone')||'"auto"');if(zone&&zone!=='auto')hour=Number(new Intl.DateTimeFormat('en-US',{timeZone:zone,hour:'numeric',hourCycle:'h23'}).format(new Date()))}catch{}return hour<12?'Good morning!':hour<17?'Good afternoon!':'Good evening!'}
 const phrases=[greeting,'What are we playing today?','teague is lowkey a cool guy','hola','its a great day to play games in class because i have nothing else to do','One more round?','Your next favorite game is right here.','Grab a friend and run it back.','Big game, small break.','Welcome back. Pick something good.'];
 let phrase=0,letter=0,erasing=false,text=greeting();
 if(tagline){tagline.style.minHeight='2.8em';tagline.setAttribute('aria-label',text);if(reduced)tagline.textContent=text;else{const tick=()=>{letter+=erasing?-1:1;tagline.textContent=text.slice(0,letter)||'\u00a0';let delay=erasing?25:65;if(letter===text.length&&!erasing){erasing=true;delay=Math.max(2600,text.length*55)}else if(letter===0){erasing=false;phrase=(phrase+1)%phrases.length;text=typeof phrases[phrase]==='function'?phrases[phrase]():phrases[phrase];tagline.setAttribute('aria-label',text);delay=450}setTimeout(tick,delay)};tick()}}
 const toggle=document.createElement('button');toggle.className='sidebar-toggle';toggle.type='button';toggle.textContent='☰';toggle.setAttribute('aria-label','Toggle sidebar');document.body.append(toggle);let closed=false;try{closed=JSON.parse(localStorage.getItem('sg-sidebar-closed')||'false')===true}catch{}function apply(){document.body.classList.toggle('sidebar-collapsed',closed);toggle.setAttribute('aria-expanded',String(!closed))}apply();document.addEventListener('simplegames:settings-reset',()=>{closed=false;apply()});toggle.onclick=()=>{closed=!closed;try{localStorage.setItem('sg-sidebar-closed',JSON.stringify(closed))}catch{}apply()};
 // Keep the cat favicon static; the tab title still types.
 if(!reduced){let n=0;setInterval(()=>{n=(n+1)%16;document.title='Simple Games'.slice(0,n)||'\u200b'},450)}
})();
