(() => {
 const setting=document.querySelector('#message-popups'),mode=document.querySelector('#server-notifications');setting.checked=JSON.parse(localStorage.getItem('sg-message-popups')||'true');mode.value=JSON.parse(localStorage.getItem('sg-server-notifications')||'"pings"');setting.onchange=()=>localStorage.setItem('sg-message-popups',JSON.stringify(setting.checked));mode.onchange=()=>localStorage.setItem('sg-server-notifications',JSON.stringify(mode.value));
 document.addEventListener('simplegames:settings-reset',()=>{setting.checked=true;mode.value='pings';stack.replaceChildren()});
 const stack=document.createElement('div');stack.className='message-popup-stack';stack.setAttribute('aria-live','polite');document.body.append(stack);
 document.addEventListener('simplegames:notification',event=>{if(!setting.checked||event.detail.muted)return;const data=event.detail;while(stack.children.length>=3)stack.firstElementChild.remove();const card=document.createElement('section');card.className='message-popup';const name=document.createElement('strong');name.textContent=data.name;const text=document.createElement('p');text.textContent=data.text;const close=document.createElement('button');close.textContent='×';close.className='popup-close';close.setAttribute('aria-label','Dismiss notification');close.onclick=()=>card.remove();const hint=document.createElement('small');hint.textContent='Turn off message pop-ups in Settings.';card.append(name,text,close);
 if(data.reply){const form=document.createElement('form'),field=document.createElement('input'),send=document.createElement('button'),feedback=document.createElement('p');field.placeholder='Reply…';field.maxLength=500;field.required=true;field.setAttribute('aria-label','Quick reply');send.textContent='Send';send.className='secondary-button';feedback.setAttribute('aria-live','polite');form.append(field,send);form.onsubmit=async e=>{e.preventDefault();if(!field.value.trim())return;send.disabled=true;try{await data.reply(field.value.trim());card.remove()}catch(error){feedback.textContent=error.message||'Reply failed.';send.disabled=false}};card.append(form,feedback)}card.append(hint);stack.append(card);setTimeout(()=>{if(!card.contains(document.activeElement))card.remove()},20000);
 });
 document.addEventListener('simplegames:auth',()=>stack.replaceChildren());
 const friends=document.querySelector('[data-dashboard-action="account"]'),servers=document.querySelector('[data-dashboard-action="servers"]');for(const button of [friends,servers]){const badge=document.createElement('span');badge.className='home-unread-badge';badge.hidden=true;button.append(badge)}
 const account=document.querySelector('#account-unread');new MutationObserver(()=>{const badge=friends.querySelector('.home-unread-badge');badge.textContent=account.textContent;badge.hidden=account.hidden||Number(account.textContent)===0}).observe(account,{attributes:true,childList:true,characterData:true,subtree:true});
 document.addEventListener('simplegames:server-unread',event=>{const badge=servers.querySelector('.home-unread-badge');badge.textContent=event.detail.count;badge.hidden=!event.detail.count});
})();
