import { getApp, getApps, initializeApp } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js";
import { getAuth, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js";
import { addDoc, arrayRemove, arrayUnion, collection, deleteDoc, doc, getDoc, getFirestore, limit, onSnapshot, orderBy, query, serverTimestamp, setDoc, updateDoc, where } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js";
import{serverNotificationAllowed}from'./notification-logic.js?v=1';
import{canReadChannel,canSendChannel,channelEditor}from'./channel-permissions.js?v=1';
import{sendServerInvite,listenServerInvites}from'./server-invites.js?v=1';
const config={apiKey:"AIzaSyDzJu7zyLTZWwffbS5wcxAGym5orePvNKg",authDomain:"simplegames-23c2c.firebaseapp.com",projectId:"simplegames-23c2c",storageBucket:"simplegames-23c2c.firebasestorage.app",messagingSenderId:"993873419513",appId:"1:993873419513:web:14e22dfff6d7f0c7051628",measurementId:"G-NC81W7MYG0"};
const app=getApps().length?getApp():initializeApp(config),auth=getAuth(app),db=getFirestore(app),$=selector=>document.querySelector(selector);
const panel=$("#server-panel"),layout=panel.querySelector(".server-layout"),list=$("#server-list"),channels=$("#channel-list"),messages=$("#server-messages"),members=$("#server-members"),status=$("#server-status"),discoverList=$("#server-discover-list");
let user=null,myServers=[],publicServers=[],activeServer=null,activeChannel="general",profiles=new Map(),stopMine=()=>{},stopMessages=()=>{};
let notificationStops=[],notificationSignature='',notificationUser=null,notificationProfile={};const unreadServers=new Map();
document.addEventListener('simplegames:profile',event=>notificationProfile=event.detail.profile||{});
function publishServerUnread(){if(notificationUser){try{localStorage.setItem('sg-server-unread-'+notificationUser,JSON.stringify([...unreadServers]))}catch{}}document.dispatchEvent(new CustomEvent('simplegames:server-unread',{detail:{count:[...unreadServers.values()].reduce((a,b)=>a+b,0)}}))}
function readServerChannel(serverId,channel){if(document.hidden||panel.hidden||!$('#game-overlay').hidden)return;unreadServers.delete(serverId+'/'+channel);publishServerUnread()}
function syncServerNotifications(){
 const signature=JSON.stringify([user?.uid,myServers.map(s=>[s.id,s.channels,s.memberRoles,s.channelSettings])]);if(signature===notificationSignature)return;notificationSignature=signature;notificationStops.forEach(stop=>stop());notificationStops=[];if(notificationUser!==user?.uid){unreadServers.clear();notificationUser=user?.uid;notificationProfile={};if(notificationUser){try{for(const [key,count]of JSON.parse(localStorage.getItem('sg-server-unread-'+notificationUser)||'[]'))unreadServers.set(key,count)}catch{}}publishServerUnread()}if(!user)return;const me=user.uid;
 for(const server of myServers){for(const channel of server.channels||[]){if(!canReadChannel(server,channel,me)){unreadServers.delete(server.id+'/'+channel);publishServerUnread();continue;}let ready=false,seen=new Set();const key=server.id+'/'+channel;
 notificationStops.push(onSnapshot(query(collection(db,'servers',server.id,'messages'),where('channel','==',channel)),snapshot=>{const ids=new Set(snapshot.docs.map(d=>d.id));if(!ready){seen=ids;ready=true;return}for(const entry of snapshot.docs){if(seen.has(entry.id))continue;const data=entry.data();if(data.senderId===me)continue;if(!document.hidden&&$('#game-overlay').hidden&&!panel.hidden&&activeServer?.id===server.id&&activeChannel===channel){readServerChannel(server.id,channel);continue}const mode=document.querySelector('#server-notifications').value;if(!serverNotificationAllowed(mode,data.text,notificationProfile))continue;unreadServers.set(key,(unreadServers.get(key)||0)+1);publishServerUnread();document.dispatchEvent(new CustomEvent('simplegames:notification',{detail:{name:(data.senderName||'Member')+' · '+server.name+' #'+(server.channelNames?.[channel]||channel),text:data.text,muted:notificationProfile.doNotDisturb,sound:notificationProfile.messageSound!==false,reply:async text=>{if(user?.uid!==me)throw Error('Sign in to reply.');const mine=await profile(me);await addDoc(collection(db,'servers',server.id,'messages'),{senderId:me,senderName:mine.displayName||mine.username||'Member',channel,text,createdAt:serverTimestamp()})}}}))}seen=ids},error=>{console.error('Server notifications:',error);document.dispatchEvent(new CustomEvent('simplegames:notification-error',{detail:{message:'Server notifications could not connect. Check your connection and channel permissions.'}}));say('Server notifications could not load. Check channel permissions.')}));
 }}
}
function say(text,error=true){status.textContent=text;status.style.background=error?"#b33b46":"#237a4b";clearTimeout(say.timer);say.timer=setTimeout(()=>status.textContent="",4000)}
function safe(value){return String(value??"")}
function channelLabel(id){return activeServer?.channelNames?.[id]||id}
function serverPermission(permission){if(!activeServer||!user)return false;if(activeServer.ownerUid===user.uid)return true;const role=activeServer.memberRoles?.[user.uid]||'member';return activeServer.rolePermissions?.[role]?.[permission]===true}
function ownPermission(permission){return activeServer?.ownerUid===user?.uid||activeServer?.rolePermissions?.[activeServer?.memberRoles?.[user?.uid]||'member']?.[permission]!==false}
function channelAccess(name){return canReadChannel(activeServer,name,user?.uid)}
function canSend(){return canSendChannel(activeServer,activeChannel,user?.uid)}
function refreshComposer(){const form=$('#server-message-form'),allowed=canSend();form.elements.message.disabled=!allowed;form.querySelector('button[type="submit"]').disabled=!allowed;form.elements.message.placeholder=allowed?`Message #${channelLabel(activeChannel)}`:'Read-only channel — you cannot send messages';}
async function serverCommand(text){
  const [command,arg]=text.trim().split(/\s+/);if(!['/lock','/unlock','/kick','/ban','/unban','/help'].includes(command))return false;
  if(command==='/help'){say('/lock · /unlock · /kick username · /ban username · /unban username. Moderation commands are owner-only.',false);return true}
  if(activeServer.ownerUid!==user.uid)throw Error('Only the server owner can use moderation commands.');
  const ref=doc(db,'servers',activeServer.id);
  if(command==='/lock'||command==='/unlock'){await updateDoc(ref,{[`channelSettings.${activeChannel}.locked`]:command==='/lock',updatedAt:serverTimestamp()});say(command==='/lock'?'Channel locked.':'Channel unlocked.',false);return true}
  if(!arg)throw Error('Enter a username after the command.');const uid=await usernameUid(arg.replace(/^@/,''));if(!uid)throw Error('Username not found.');if(uid===activeServer.ownerUid)throw Error('The owner cannot be removed.');
  if(command==='/unban'){await updateDoc(ref,{banned:arrayRemove(uid),updatedAt:serverTimestamp()});say('Ban removed.',false);return true}
  if(!activeServer.members.includes(uid))throw Error('That person is not in this server.');
  const changes={members:arrayRemove(uid),updatedAt:serverTimestamp()};if(command==='/ban')changes.banned=arrayUnion(uid);await updateDoc(ref,changes);say(command==='/ban'?'Member banned.':'Member kicked.',false);return true;
}
function paintAvatar(element,data){element.replaceChildren();if(data.avatarImage){const image=document.createElement('img');image.src=data.avatarImage;image.alt='';element.append(image)}else element.textContent=(data.displayName||data.username||'?')[0].toUpperCase()}
function openServerProfile(uid,data){document.dispatchEvent(new CustomEvent('simplegames:open-profile',{detail:{uid,profile:data}}))}
const roleForm=document.querySelector('#server-role-form');
const rolePreview=document.createElement('span');rolePreview.className='role-chip';rolePreview.setAttribute('aria-live','polite');roleForm?.append(rolePreview);
function previewRole(){const color=roleForm.elements.color.value;rolePreview.textContent=(roleForm.elements.name.value||'Role preview')+' '+color;rolePreview.style.color=color;rolePreview.style.borderColor=color}
roleForm?.addEventListener('input',previewRole);roleForm?.addEventListener('reset',()=>setTimeout(previewRole,0));if(roleForm)previewRole();
async function usernameUid(name){const snap=await getDoc(doc(db,"usernames",safe(name).trim().toLowerCase()));return snap.exists()?snap.data().uid:null}
async function profile(uid){if(profiles.has(uid))return profiles.get(uid);const snap=await getDoc(doc(db,"users",uid)),data=snap.exists()?snap.data():{displayName:"Member",username:"member"};profiles.set(uid,data);return data}
function closeDialogs(){document.querySelectorAll(".server-dialog").forEach(dialog=>dialog.hidden=true)}
function appendMessageTools(row,data){
  const tools=document.createElement('div');tools.className='message-tools';
  if(data.senderId===user.uid&&ownPermission('editOwnMessages')){const edit=document.createElement('button');edit.className='message-tool';edit.textContent='Edit';edit.onclick=()=>{
    if(row.querySelector('.server-message-editor'))return;
    const editor=document.createElement('form');editor.className='server-message-editor';const field=document.createElement('textarea');field.value=data.text;field.maxLength=500;field.required=true;field.setAttribute('aria-label','Edit message');
    const save=document.createElement('button');save.type='submit';save.className='secondary-button';save.textContent='Save';const cancel=document.createElement('button');cancel.type='button';cancel.className='secondary-button';cancel.textContent='Cancel';
    const feedback=document.createElement('p');feedback.setAttribute('aria-live','polite');const original=row.querySelector('p');original.hidden=true;edit.disabled=true;
    function close(){editor.remove();original.hidden=false;edit.disabled=false}
    cancel.onclick=close;field.onkeydown=event=>{if(event.key==='Escape'){event.stopPropagation();close()}};
    editor.onsubmit=async event=>{event.preventDefault();const text=field.value.trim();if(!text){feedback.textContent='Enter a message.';return}save.disabled=true;cancel.disabled=true;try{await updateDoc(data._ref,{text,editedAt:serverTimestamp()});close()}catch(error){feedback.textContent=error.code==='permission-denied'?'Editing was blocked. Publish the latest Firestore rules and check channel permissions.':error.message;save.disabled=false;cancel.disabled=false}};
    editor.append(field,save,cancel,feedback);row.lastElementChild.append(editor);field.focus();field.setSelectionRange(field.value.length,field.value.length);
  };tools.append(edit)}
  if(data.senderId===user.uid&&ownPermission('deleteOwnMessages')||serverPermission('manageMessages')){const remove=document.createElement('button');remove.className='message-tool';remove.textContent='Delete';remove.onclick=()=>{
    if(row.querySelector('.server-delete-confirm'))return;
    const box=document.createElement('div');box.className='server-delete-confirm';const label=document.createElement('span');label.textContent='Delete this message?';
    const yes=document.createElement('button');yes.className='secondary-button';yes.textContent='Delete';const no=document.createElement('button');no.className='secondary-button';no.textContent='Cancel';const feedback=document.createElement('p');feedback.setAttribute('aria-live','polite');remove.disabled=true;
    no.onclick=()=>{box.remove();remove.disabled=false};yes.onclick=async()=>{yes.disabled=true;no.disabled=true;try{await deleteDoc(data._ref);row.remove()}catch(error){feedback.textContent=error.code==='permission-denied'?'Deletion was blocked. Check the latest rules and your role permissions.':error.message;yes.disabled=false;no.disabled=false}};
    box.append(label,yes,no,feedback);row.lastElementChild.append(box);no.focus();
  };tools.append(remove)}
  if(data.editedAt){const label=document.createElement('small');label.textContent='edited';tools.append(label)}row.lastElementChild.append(tools);
}
function editChannel(name){
  if(activeServer.ownerUid!==user.uid)return;
  const dialog=document.createElement('div');dialog.className='server-dialog';const card=document.createElement('div');card.className='server-dialog-card';const heading=document.createElement('h3');heading.textContent=`Edit #${name}`;
  const serverId=activeServer.id,rename=document.createElement('input');rename.value=channelLabel(name);rename.maxLength=32;rename.setAttribute('aria-label','Channel name');
  const lock=document.createElement('input');lock.type='checkbox';lock.checked=!!activeServer.channelSettings?.[name]?.locked;const label=document.createElement('label');label.append(lock,' Lock channel (moderators can still send)');
  const permissions=channelEditor(activeServer,name,card,profiles);
  const save=document.createElement('button');save.className='submit-button';save.textContent='Save channel';save.onclick=async()=>{const title=rename.value.trim().toLowerCase().replace(/[^a-z0-9-]/g,'-').replace(/-+/g,'-').replace(/^-|-$/g,'');if(!title)return say('Enter a channel name.');if(activeServer.channels.some(id=>id!==name&&channelLabel(id)===title))return say('A channel already has that name.');save.disabled=true;try{await updateDoc(doc(db,'servers',serverId),{[`channelNames.${name}`]:title,[`channelSettings.${name}`]:{locked:lock.checked,...permissions()},updatedAt:serverTimestamp()});dialog.remove();say('Channel saved.',false)}catch(error){save.disabled=false;say(error.message)}};
  const remove=document.createElement('button');remove.className='secondary-button';remove.textContent='Delete channel';remove.style.color='#ff8585';const confirmation=document.createElement('div');confirmation.hidden=true;const warning=document.createElement('p');warning.textContent='Remove this channel from the server? Its old messages remain stored but will no longer be accessible.';const yes=document.createElement('button');yes.className='secondary-button';yes.textContent='Delete channel';const no=document.createElement('button');no.className='secondary-button';no.textContent='Keep channel';no.onclick=()=>confirmation.hidden=true;remove.onclick=()=>{confirmation.hidden=false;no.focus()};yes.onclick=async()=>{if(activeServer.id!==serverId)return;if(activeServer.channels.length<=1)return say('Keep at least one channel in the server.');yes.disabled=true;try{await updateDoc(doc(db,'servers',serverId),{channels:arrayRemove(name),updatedAt:serverTimestamp()});dialog.remove();say('Channel removed.',false)}catch(error){yes.disabled=false;say(error.message)}};confirmation.append(warning,yes,no);
  const close=document.createElement('button');close.className='secondary-button';close.textContent='Cancel';close.onclick=()=>dialog.remove();card.prepend(heading,rename,label);card.append(save,remove,confirmation,close);dialog.append(card);panel.append(dialog);dialog.onclick=event=>{if(event.target===dialog)dialog.remove()};rename.focus();
}
function editRolePermissions(role){
  if(activeServer.ownerUid!==user.uid||role.id==='owner')return;
  const dialog=document.createElement('div');dialog.className='server-dialog';const card=document.createElement('div');card.className='server-dialog-card';const heading=document.createElement('h3');heading.textContent=`${role.name} permissions`;card.append(heading);
  const serverId=activeServer.id,name=document.createElement('input'),color=document.createElement('input'),preview=document.createElement('span');name.value=role.name;name.maxLength=32;name.setAttribute('aria-label','Role name');color.type='color';color.value=/^#[0-9a-f]{6}$/i.test(role.color)?role.color:'#8b96a8';color.setAttribute('aria-label','Role color');preview.className='role-chip';function previewEdit(){preview.textContent=name.value||'Role preview';preview.style.color=preview.style.borderColor=color.value}name.oninput=color.oninput=previewEdit;previewEdit();card.append(name,color,preview);
  const send=document.createElement('input');send.type='checkbox';send.checked=activeServer.rolePermissions?.[role.id]?.sendMessages!==false;const manage=document.createElement('input');manage.type='checkbox';manage.checked=activeServer.rolePermissions?.[role.id]?.manageMessages===true;
  const edit=document.createElement('input');edit.type='checkbox';edit.checked=activeServer.rolePermissions?.[role.id]?.editOwnMessages!==false;const remove=document.createElement('input');remove.type='checkbox';remove.checked=activeServer.rolePermissions?.[role.id]?.deleteOwnMessages!==false;
  for(const [input,text]of [[send,'Send messages'],[edit,'Edit own messages'],[remove,'Delete own messages'],[manage,'Delete other messages / send in locked channels']]){const label=document.createElement('label');label.append(input,text);card.append(label)}
  const save=document.createElement('button');save.className='submit-button';save.textContent='Save role';save.onclick=async()=>{const title=name.value.trim();if(!title)return say('Enter a role name.');if(activeServer?.id!==serverId)return say('Open this server again before saving.');if(activeServer.roles.some(item=>item.id!==role.id&&item.name.toLowerCase()===title.toLowerCase()))return say('Choose a unique role name.');save.disabled=true;try{await updateDoc(doc(db,'servers',serverId),{roles:activeServer.roles.map(item=>item.id===role.id?{...item,name:title,color:color.value}:item),[`rolePermissions.${role.id}`]:{sendMessages:send.checked,editOwnMessages:edit.checked,deleteOwnMessages:remove.checked,manageMessages:manage.checked},updatedAt:serverTimestamp()});dialog.remove();renderRoles();say('Role saved.',false)}catch(error){save.disabled=false;say(error.message)}};
  const cancel=document.createElement('button');cancel.className='secondary-button';cancel.textContent='Cancel';cancel.onclick=()=>dialog.remove();card.append(save,cancel);dialog.append(card);panel.append(dialog);save.focus();
}
function showDiscover(){activeServer=null;stopMessages();layout.classList.add("discover-mode");$("#channel-pane").hidden=true;$("#server-discover").hidden=false;$("#server-chat-heading").hidden=true;messages.hidden=true;$("#server-message-form").hidden=true;panel.querySelector(".member-pane").hidden=true;$("#server-discover-open").classList.add("active");$("#server-my-open").classList.remove("active");renderDiscover()}
function showMine(){layout.classList.remove("discover-mode");$("#server-discover").hidden=true;panel.querySelector(".member-pane").hidden=false;$("#server-discover-open").classList.remove("active");$("#server-my-open").classList.add("active");if(myServers.length)selectServer(myServers[0].id);else{$("#channel-pane").hidden=false;messages.hidden=false;messages.innerHTML='<div class="server-empty"><h3>No servers yet</h3><p>Create one or join one from Discover.</p></div>'}}
$("#servers-open")?.addEventListener("click",()=>{panel.hidden=false;showDiscover()});$("#servers-close")?.addEventListener("click",()=>panel.hidden=true);$("#server-discover-open")?.addEventListener("click",showDiscover);$("#server-my-open")?.addEventListener("click",showMine);
$("#server-create-open")?.addEventListener("click",()=>{if(!user)return say("Log in through Account first.");$("#server-create-dialog").hidden=false});$("#server-invite-open")?.addEventListener("click",()=>$("#server-invite-dialog").hidden=false);$("#server-roles-open")?.addEventListener("click",()=>{renderRoles();$("#server-roles-dialog").hidden=false});document.querySelectorAll("[data-server-dialog-close]").forEach(button=>button.addEventListener("click",closeDialogs));
onSnapshot(query(collection(db,"servers"),where("isPublic","==",true),limit(100)),snap=>{publicServers=snap.docs.map(item=>({id:item.id,...item.data()}));renderDiscover()},error=>say(error.message));
onAuthStateChanged(auth,next=>{user=next;listenServerInvites(db,next);stopMine();myServers=[];renderMine();syncServerNotifications();if(!user){renderDiscover();return}stopMine=onSnapshot(query(collection(db,"servers"),where("members","array-contains",user.uid)),snap=>{myServers=snap.docs.map(item=>({id:item.id,...item.data()})).sort((a,b)=>safe(a.name).localeCompare(safe(b.name)));renderMine();syncServerNotifications();if(activeServer){activeServer=myServers.find(item=>item.id===activeServer.id)||null;if(activeServer)selectServer(activeServer.id,false);else showDiscover()}},error=>say(error.message))});
function renderMine(){list.innerHTML="";if(!user)return list.innerHTML="<p>Log in to see yours.</p>";if(!myServers.length)return list.innerHTML="<p>No servers yet.</p>";myServers.forEach(server=>{const button=document.createElement("button");button.type="button";button.textContent=server.name;button.classList.toggle("active",activeServer?.id===server.id);button.onclick=()=>selectServer(server.id);list.append(button)})}
function renderDiscover(){if(!discoverList)return;const mode=$("#server-sort").value,sorted=[...publicServers].sort((a,b)=>mode==="az"?safe(a.name).localeCompare(safe(b.name)):mode==="newest"?(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0):(b.members?.length||0)-(a.members?.length||0));discoverList.innerHTML="";if(!sorted.length)return discoverList.innerHTML="<p>No public servers yet. Be the first to create one.</p>";sorted.forEach(server=>{const joined=!!user&&server.members?.includes(user.uid),card=document.createElement("article");card.className="discover-card";card.innerHTML='<div class="discover-card-icon"></div><div><span class="discover-category"></span><h3></h3><p></p><small></small></div><button class="submit-button" type="button"></button>';card.querySelector(".discover-card-icon").textContent=server.name?.[0]?.toUpperCase()||"S";card.querySelector(".discover-category").textContent=server.category||"Community";card.querySelector("h3").textContent=server.name;card.querySelector("p").textContent=server.description||"A Simple Games community.";card.querySelector("small").textContent=`${server.members?.length||1} member${server.members?.length===1?"":"s"}`;const button=card.querySelector("button");button.textContent=joined?"Open":"Join";button.onclick=()=>joined?selectServer(server.id):joinServer(server);discoverList.append(card)})}
$("#server-sort")?.addEventListener("change",renderDiscover);
async function joinServer(server){if(!user)return say("Log in through Account to join.");if(server.banned?.includes(user.uid))return say("You are banned from this server.");try{await updateDoc(doc(db,"servers",server.id),{members:arrayUnion(user.uid),[`memberRoles.${user.uid}`]:"member",updatedAt:serverTimestamp()});say("Server joined.",false);setTimeout(()=>selectServer(server.id),250)}catch(error){say(error.message)}}
async function selectServer(id,reset=true){const server=myServers.find(item=>item.id===id)||publicServers.find(item=>item.id===id);if(!server||!user||!server.members?.includes(user.uid))return say("Join this server first.");activeServer=server;if(reset||!server.channels?.includes(activeChannel))activeChannel=server.channels?.[0]||"general";if(!channelAccess(activeChannel))activeChannel=server.channels.find(channelAccess)||"";layout.classList.remove("discover-mode");$("#server-discover").hidden=true;$("#channel-pane").hidden=false;panel.querySelector(".member-pane").hidden=false;$("#server-chat-heading").hidden=false;messages.hidden=false;$("#server-message-form").hidden=false;$("#server-name").textContent=server.name;$("#channel-title").textContent=channelLabel(activeChannel);$("#server-message-form input").placeholder=`Message #${channelLabel(activeChannel)}`;const owner=server.ownerUid===user.uid;$("#channel-form").hidden=!owner;$("#server-invite-open").hidden=!owner;$("#server-roles-open").hidden=!owner;$("#server-leave").hidden=false;$("#server-leave").textContent=owner?"Delete server":"Leave server";renderMine();renderChannels();await renderMembers();if(activeChannel)listenMessages();else{stopMessages();messages.textContent="No channels are available for your role.";$("#server-message-form").hidden=true}}
function renderChannels(){channels.innerHTML="";(activeServer.channels||["general"]).filter(channelAccess).forEach(name=>{const row=document.createElement("div");row.className="server-channel-row";const button=document.createElement("button");button.className="server-channel-name";button.type="button";button.textContent=`# ${channelLabel(name)}`;button.classList.toggle("active",name===activeChannel);button.onclick=()=>{activeChannel=name;$("#channel-title").textContent=channelLabel(name);$("#server-message-form input").placeholder=`Message #${channelLabel(name)}`;renderChannels();listenMessages()};row.append(button);if(activeServer.ownerUid===user.uid){const edit=document.createElement("button");edit.type="button";edit.className="server-channel-edit";edit.textContent="⚙";edit.setAttribute("aria-label",`Edit #${channelLabel(name)}`);edit.title=`Edit #${channelLabel(name)}`;edit.onclick=()=>editChannel(name);row.append(edit)}channels.append(row)})}
async function renderMembers(){members.replaceChildren();for(const uid of activeServer.members||[]){const data=await profile(uid),name=data.displayName||data.username||"Member",role=(activeServer.roles||[]).find(item=>item.id===(activeServer.memberRoles?.[uid]||"member")),row=document.createElement("div");row.className="server-member";row.innerHTML='<button type="button" class="server-member-avatar" aria-label="View profile"></button><span><strong></strong><small></small></span>';paintAvatar(row.children[0],data);row.children[0].onclick=()=>openServerProfile(uid,data);row.querySelector("strong").textContent=name;row.querySelector("strong").style.color=role?.color||"";row.querySelector("small").textContent=role?.name||(uid===activeServer.ownerUid?"Owner":"Member");row.querySelector("small").style.color=role?.color||"";members.append(row)}}
function listenMessages(){stopMessages();refreshComposer();readServerChannel(activeServer.id,activeChannel);messages.innerHTML="<p>Loading messages…</p>";stopMessages=onSnapshot(query(collection(db,"servers",activeServer.id,"messages"),where("channel","==",activeChannel)),snap=>{messages.innerHTML="";const visible=snap.docs.map(item=>({...item.data(),_ref:item.ref})).sort((a,b)=>(a.createdAt?.seconds||0)-(b.createdAt?.seconds||0));if(!visible.length)messages.innerHTML=`<div class="server-empty"><h3>Welcome to #${activeChannel}</h3><p>This is the start of the channel.</p></div>`;visible.forEach(data=>{const row=document.createElement("article"),date=data.createdAt?.toDate?.();row.className="server-message";row.innerHTML='<span class="server-message-avatar"></span><div><div class="server-message-head"><strong></strong><time></time></div><p></p></div>';row.children[0].textContent=(data.senderName||"?")[0].toUpperCase();row.children[0].role="button";row.children[0].tabIndex=0;const avatar=row.children[0];profile(data.senderId).then(person=>paintAvatar(avatar,person)).catch(()=>{});avatar.onclick=async()=>{try{openServerProfile(data.senderId,await profile(data.senderId))}catch(error){say(error.message)}};avatar.onkeydown=e=>{if(e.key==="Enter"||e.key===" ")avatar.click()};row.querySelector("strong").textContent=data.senderName||"Member";const role=activeServer.roles?.find(r=>r.id===(activeServer.memberRoles?.[data.senderId]||"member"));row.querySelector("strong").style.color=role?.color||"";row.querySelector("time").textContent=date?date.toLocaleString():"sending…";row.querySelector("p").textContent=data.text;appendMessageTools(row,data);messages.append(row)});messages.scrollTop=messages.scrollHeight},error=>say(error.message))}
$("#server-create-form")?.addEventListener("submit",async event=>{event.preventDefault();if(!user)return;const form=event.currentTarget,data=new FormData(form),names=safe(data.get("members")).split(",").map(value=>value.trim()).filter(Boolean);try{const invited=await Promise.all(names.map(usernameUid));if(invited.some(uid=>!uid))throw new Error("One or more usernames were not found.");const mine=await profile(user.uid),ref=doc(collection(db,"servers")),memberList=[user.uid],memberRoles=Object.fromEntries(memberList.map(uid=>[uid,uid===user.uid?"owner":"member"]));await setDoc(ref,{name:safe(data.get("name")).trim(),description:safe(data.get("description")).trim(),category:safe(data.get("category")),isPublic:data.get("isPublic")==="on",ownerUid:user.uid,ownerName:mine.displayName||mine.username||"Owner",members:memberList,channels:["general"],roles:[{id:"owner",name:"Owner",color:"#f0b232"},{id:"member",name:"Member",color:"#8b96a8"}],memberRoles,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});for(const uid of [...new Set(invited)]){if(uid!==user.uid)await sendServerInvite(db,{id:ref.id,name:safe(data.get('name')).trim(),members:memberList},{...mine,uid:user.uid},uid)}form.reset();form.elements.isPublic.checked=true;closeDialogs();say("Server created.",false)}catch(error){say(error.message)}});
$("#server-invite-form")?.addEventListener("submit",async event=>{event.preventDefault();const form=event.currentTarget,server=activeServer,me=user;form.querySelector('.invite-result')?.remove();try{const uid=await usernameUid(new FormData(form).get("username"));if(!uid)throw Error("Username not found.");if(server.members.includes(uid))throw Error("Already a member.");const target=await profile(uid),result=document.createElement('div');result.className='invite-result';const name=document.createElement('p');name.textContent=(target.displayName||target.username)+' · @'+target.username;const send=document.createElement('button');send.type='button';send.className='submit-button';send.textContent='Send invite';send.onclick=async()=>{send.disabled=true;try{if(user?.uid!==me.uid)throw Error('Sign in again.');const mine=await profile(me.uid);await sendServerInvite(db,server,{...mine,uid:me.uid},uid);form.reset();result.remove();closeDialogs();say('Invite sent. They can accept or decline in Friends.',false)}catch(error){send.disabled=false;say(error.message)}};result.append(name,send);form.append(result)}catch(error){say(error.message)}});
$("#channel-form")?.addEventListener("submit",async event=>{event.preventDefault();const field=event.currentTarget.elements.channel,name=field.value.trim().toLowerCase().replace(/[^a-z0-9-]/g,"-").replace(/-+/g,"-").replace(/^-|-$/g,"");if(!name)return say("Use letters, numbers, or dashes.");if(activeServer.channels.some(id=>channelLabel(id)===name))return say("That channel already exists.");const id=name+"-"+Date.now().toString(36);try{await updateDoc(doc(db,"servers",activeServer.id),{channels:arrayUnion(id),[`channelNames.${id}`]:name,updatedAt:serverTimestamp()});field.value="";activeChannel=id;say("Channel added.",false)}catch(error){say(error.message)}});
$("#server-message-form")?.addEventListener("submit",async event=>{event.preventDefault();const field=event.currentTarget.elements.message,text=field.value.trim();if(!text||!activeServer)return;field.value="";try{if(await serverCommand(text))return;if(!canSend())throw Error("This channel is locked or your role cannot send messages.");const mine=await profile(user.uid);await addDoc(collection(db,"servers",activeServer.id,"messages"),{senderId:user.uid,senderName:mine.displayName||mine.username||"Member",channel:activeChannel,text,createdAt:serverTimestamp()})}catch(error){field.value=text;say(error.message)}});
function renderRoles(){const roleList=$("#server-role-list"),memberSelect=$("#server-role-assign-form").elements.member,roleSelect=$("#server-role-assign-form").elements.role;roleList.innerHTML="";memberSelect.innerHTML="";roleSelect.innerHTML="";(activeServer.roles||[]).forEach(role=>{const chip=document.createElement("span"),option=document.createElement("option");chip.className="role-chip";chip.textContent=role.name;chip.style.borderColor=chip.style.color=role.color;roleList.append(chip);if(role.id!=="owner"){const permissions=document.createElement("button");permissions.className="secondary-button";permissions.textContent=`Edit ${role.name}`;permissions.onclick=()=>editRolePermissions(role);roleList.append(permissions)}option.value=role.id;option.textContent=role.name;roleSelect.append(option)});(activeServer.members||[]).forEach(async uid=>{const data=await profile(uid),option=document.createElement("option");option.value=uid;option.textContent=data.displayName||data.username;memberSelect.append(option)})}
$("#server-role-form")?.addEventListener("submit",async event=>{event.preventDefault();const form=event.currentTarget,data=new FormData(form),name=safe(data.get("name")).trim(),id=name.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");if(!id)return;if(["owner","member"].includes(id)||activeServer.roles?.some(role=>role.id===id))return say("Choose a unique role name.");try{await updateDoc(doc(db,"servers",activeServer.id),{roles:arrayUnion({id,name,color:safe(data.get("color"))}),updatedAt:serverTimestamp()});form.reset();say("Role created.",false);closeDialogs()}catch(error){say(error.message)}});
$("#server-role-assign-form")?.addEventListener("submit",async event=>{event.preventDefault();const data=new FormData(event.currentTarget);try{await updateDoc(doc(db,"servers",activeServer.id),{[`memberRoles.${data.get("member")}`]:data.get("role"),updatedAt:serverTimestamp()});say("Role assigned.",false);closeDialogs()}catch(error){say(error.message)}});
$("#server-leave")?.addEventListener("click",async()=>{if(!activeServer)return;if(activeServer.ownerUid===user.uid){if(!confirm("Delete this server for everyone?"))return;await deleteDoc(doc(db,"servers",activeServer.id));say("Server deleted.",false)}else{if(!confirm("Leave this server?"))return;await updateDoc(doc(db,"servers",activeServer.id),{members:arrayRemove(user.uid),updatedAt:serverTimestamp()});say("You left the server.",false)}showDiscover()});
