import { getApp, getApps, initializeApp } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js";
import { getAuth, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js";
import { addDoc, arrayRemove, arrayUnion, collection, deleteDoc, doc, getDoc, getDocFromServer, getDocs, getFirestore, limit, onSnapshot, orderBy, query, runTransaction, Timestamp, serverTimestamp, setDoc, updateDoc, where } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js";
import{serverNotificationAllowed,freshNotification}from'./notification-logic.js?v=2';
import{findUser}from'./user-lookup.js?v=1';
const notificationSessionStarted=Date.now();
const profileStops=new Map();
import{canReadChannel,canSendChannel,channelEditor}from'./channel-permissions.js?v=5';
import{COMMANDS,canUseCommand,commandChanges,timedOut,roleRank,canTarget}from'./server-commands.js?v=2';
import{sendServerInvite,listenServerInvites}from'./server-invites.js?v=1';
import{showServerProfile,serverIcon}from'./server-branding.js?v=2';
import{showHangouts}from'./voice-hangouts.js?v=2';
const config={apiKey:"AIzaSyDzJu7zyLTZWwffbS5wcxAGym5orePvNKg",authDomain:"simplegames-23c2c.firebaseapp.com",projectId:"simplegames-23c2c",storageBucket:"simplegames-23c2c.firebasestorage.app",messagingSenderId:"993873419513",appId:"1:993873419513:web:14e22dfff6d7f0c7051628",measurementId:"G-NC81W7MYG0"};
const app=getApps().length?getApp():initializeApp(config),auth=getAuth(app),db=getFirestore(app),$=selector=>document.querySelector(selector);
const panel=$("#server-panel"),layout=panel.querySelector(".server-layout"),list=$("#server-list"),channels=$("#channel-list"),messages=$("#server-messages"),members=$("#server-members"),status=$("#server-status"),discoverList=$("#server-discover-list");
const serverProfileButton=document.createElement('button');serverProfileButton.className='secondary-button';serverProfileButton.textContent='Server profile';serverProfileButton.type='button';serverProfileButton.onclick=()=>{if(activeServer)showServerProfile(db,activeServer,user.uid,say)};$('#channel-pane').prepend(serverProfileButton);
let memberRenderVersion=0;
let user=null,myServers=[],publicServers=[],activeServer=null,activeChannel="general",profiles=new Map(),stopMine=()=>{},stopMessages=()=>{};
let notificationStops=[],notificationSignature='',notificationUser=null,notificationProfile={};const unreadServers=new Map();
document.addEventListener('simplegames:profile',event=>notificationProfile=event.detail.profile||{});
function publishServerUnread(){if(notificationUser){try{localStorage.setItem('sg-server-unread-'+notificationUser,JSON.stringify([...unreadServers]))}catch{}}document.dispatchEvent(new CustomEvent('simplegames:server-unread',{detail:{count:[...unreadServers.values()].reduce((a,b)=>a+b,0)}}))}
function readServerChannel(serverId,channel){if(document.hidden||panel.hidden||!$('#game-overlay').hidden)return;unreadServers.delete(serverId+'/'+channel);publishServerUnread()}
function syncServerNotifications(){
 const signature=JSON.stringify([user?.uid,myServers.map(s=>[s.id,s.channels,s.memberRoles,s.channelSettings])]);if(signature===notificationSignature)return;notificationSignature=signature;notificationStops.forEach(stop=>stop());notificationStops=[];if(notificationUser!==user?.uid){unreadServers.clear();notificationUser=user?.uid;notificationProfile={};if(notificationUser){try{for(const [key,count]of JSON.parse(localStorage.getItem('sg-server-unread-'+notificationUser)||'[]'))unreadServers.set(key,count)}catch{}}publishServerUnread()}if(!user)return;const me=user.uid;
 for(const server of myServers){for(const channel of server.channels||[]){if(!canReadChannel(server,channel,me)){unreadServers.delete(server.id+'/'+channel);publishServerUnread();continue;}let ready=false,seen=new Set();const key=server.id+'/'+channel;
 notificationStops.push(onSnapshot(query(collection(db,'servers',server.id,'messages'),where('channel','==',channel)),snapshot=>{const ids=new Set(snapshot.docs.map(d=>d.id));if(!ready){seen=ids;ready=true;return}for(const entry of snapshot.docs){if(seen.has(entry.id))continue;const data=entry.data();if(data.senderId===me||!freshNotification(data.createdAt,notificationSessionStarted))continue;if(!document.hidden&&$('#game-overlay').hidden&&!panel.hidden&&activeServer?.id===server.id&&activeChannel===channel){readServerChannel(server.id,channel);continue}const mode=document.querySelector('#server-notifications').value;if(!serverNotificationAllowed(mode,data.text,notificationProfile))continue;unreadServers.set(key,(unreadServers.get(key)||0)+1);publishServerUnread();document.dispatchEvent(new CustomEvent('simplegames:notification',{detail:{name:(data.senderName||'Member')+' · '+server.name+' #'+(server.channelNames?.[channel]||channel),text:data.text,muted:notificationProfile.doNotDisturb,sound:notificationProfile.messageSound!==false,reply:async text=>{if(user?.uid!==me)throw Error('Sign in to reply.');const mine=await profile(me);await addDoc(collection(db,'servers',server.id,'messages'),{senderId:me,senderName:mine.displayName||mine.username||'Member',channel,text,createdAt:serverTimestamp()})}}}))}seen=ids},error=>{console.error('Server notifications:',error);document.dispatchEvent(new CustomEvent('simplegames:notification-error',{detail:{message:'Server notifications could not connect. Check your connection and channel permissions.'}}));say('Server notifications could not load. Check channel permissions.')}));
 }}
}
function say(text,error=true){status.textContent=text;status.style.background=error?"#b33b46":"#237a4b";clearTimeout(say.timer);say.timer=setTimeout(()=>status.textContent="",4000)}
function safe(value){return String(value??"")}
function channelLabel(id){return activeServer?.channelNames?.[id]||id}
function serverPermission(permission){if(!activeServer||!user)return false;if(activeServer.ownerUid===user.uid)return true;const role=activeServer.memberRoles?.[user.uid]||'member';return activeServer.rolePermissions?.[role]?.[permission]===true}
function ownPermission(permission){return activeServer?.ownerUid===user?.uid||activeServer?.rolePermissions?.[activeServer?.memberRoles?.[user?.uid]||'member']?.[permission]!==false}
function channelAccess(name){return canReadChannel(activeServer,name,user?.uid)}
function canSend(){return canSendChannel(activeServer,activeChannel,user?.uid)}
const commandMenu=document.createElement('div');commandMenu.className='server-command-menu';commandMenu.hidden=true;commandMenu.setAttribute('aria-label','Available commands');$('#server-message-form').prepend(commandMenu);
const commandStyle=document.createElement('style');commandStyle.textContent='.server-command-menu{grid-column:1/-1;max-height:210px;overflow:auto;border:1px solid #333;border-radius:8px;padding:8px;background:#101010;display:flex;flex-direction:column;gap:4px}.server-command-menu[hidden]{display:none}.server-command-menu button{text-align:left;padding:8px;font:inherit;color:inherit;background:transparent;border:0;border-radius:5px}.server-command-menu button:hover{background:#222}.channel-command-settings{border:1px solid #333;border-radius:8px;margin:12px 0;padding:12px}.channel-command-settings summary{cursor:pointer;padding:6px 0}';document.head.append(commandStyle);
function availableCommands(){return COMMANDS.filter(command=>canUseCommand(activeServer,activeChannel,user?.uid,command.name))}
function suggestCommands(){const field=$('#server-message-form').elements.message,text=field.value.trim();commandMenu.replaceChildren();commandMenu.hidden=!text.startsWith('/')||text.includes(' ')||!activeServer;if(commandMenu.hidden)return;for(const command of availableCommands().filter(command=>('/'+command.name).startsWith(text.toLowerCase()))){const button=document.createElement('button');button.type='button';button.textContent=command.usage+' — '+command.description;button.onclick=()=>{commandMenu.hidden=true;openCommandDialog(command.name).catch(error=>say(error.message))};commandMenu.append(button)}if(!commandMenu.children.length){commandMenu.textContent='No matching commands available for your role.'}}
$('#server-message-form').elements.message.addEventListener('input',suggestCommands);

async function openCommandDialog(name,arg='',initialDuration='10m'){
 const command=COMMANDS.find(item=>item.name===name);
 if(!command||!canUseCommand(activeServer,activeChannel,user?.uid,name))throw Error('This command is not available for your role.');
 document.querySelector('#server-command-dialog')?.close();
 const context={serverId:activeServer.id,channel:activeChannel,actor:user.uid},server=activeServer,needsMember=!['lock','unlock'].includes(name);
 const dialog=document.createElement('dialog');dialog.id='server-command-dialog';dialog.className='server-command-dialog';dialog.setAttribute('aria-labelledby','server-command-title');
 const form=document.createElement('form'),heading=document.createElement('h2'),description=document.createElement('p');
 heading.id='server-command-title';heading.textContent='/'+name;description.textContent=command.description+'. Review your selection before confirming.';form.append(heading,description);
 let chosen='',people=[],duration=null;
 const result=document.createElement('p');result.setAttribute('role','status');
 const confirm=document.createElement('button');confirm.type='submit';confirm.className='submit-button';confirm.textContent='Confirm '+name;confirm.disabled=needsMember;
 if(needsMember){
  const label=document.createElement('label'),search=document.createElement('input'),list=document.createElement('div');
  label.textContent=name==='unban'?'Select a banned member':'Select a member';search.placeholder='Search members…';search.setAttribute('aria-label','Search members');
  list.className='command-member-picker';list.setAttribute('aria-label','Members');label.append(search);form.append(label,list);
  const ids=[...new Set((name==='unban'?server.banned:server.members)||[])].filter(uid=>canTarget(server,context.actor,uid));
  const render=()=>{list.replaceChildren();for(const person of people.filter(item=>item.label.toLowerCase().includes(search.value.toLowerCase()))){
   const button=document.createElement('button');button.type='button';button.className='secondary-button';button.textContent=person.label;button.setAttribute('aria-pressed',String(chosen===person.uid));button.onclick=()=>{chosen=person.uid;confirm.disabled=false;render()};list.append(button);
  }if(!list.children.length)list.textContent=people.length?'No matching members.':'No eligible members for this command.';};
  search.oninput=render;list.textContent='Loading members…';
  Promise.all(ids.map(async uid=>{const person=await profile(uid).catch(()=>({}));return{uid,username:person.username||'',label:(person.displayName||person.username||'Profile unavailable')+(person.username?' · @'+person.username:' · '+uid.slice(0,8))}})).then(items=>{
   if(!dialog.isConnected)return;people=items;chosen=arg?people.find(item=>item.username&&item.username.toLowerCase()===arg.replace(/^@/,'').toLowerCase())?.uid||'':'';confirm.disabled=!chosen;render();
  }).catch(error=>{result.textContent=error.message});
 }
 if(name==='timeout'){const label=document.createElement('label');label.textContent='Duration';duration=document.createElement('input');duration.value=initialDuration||'10m';duration.placeholder='10m, 1h, or 1d';duration.required=true;duration.setAttribute('aria-label','Timeout duration');label.append(duration);form.append(label);}
 if(!needsMember){const note=document.createElement('p');note.textContent='Channel: #'+channelLabel(context.channel);form.append(note)}
 const cancel=document.createElement('button');cancel.type='button';cancel.className='secondary-button';cancel.textContent='Cancel';cancel.onclick=()=>dialog.close();
 form.append(result,confirm,cancel);dialog.append(form);document.body.append(dialog);
 const origin=document.activeElement;dialog.addEventListener('close',()=>{dialog.remove();origin?.focus()},{once:true});dialog.showModal();
 form.onsubmit=async event=>{event.preventDefault();if(needsMember&&!chosen)return;confirm.disabled=true;cancel.disabled=true;
  try{await serverCommand('/'+name+(needsMember?' @selected':'')+(duration?' '+duration.value.trim():''),{...context,target:chosen,label:people.find(person=>person.uid===chosen)?.label});dialog.close()}
  catch(error){result.textContent=error.message;confirm.disabled=false;cancel.disabled=false}
 };
}
const commandDialogStyle=document.createElement('style');commandDialogStyle.textContent=`
.server-command-dialog{width:min(440px,calc(100vw - 32px));box-sizing:border-box;color:var(--text,#fff);background:var(--surface,#111);border:1px solid #333;border-radius:14px;padding:24px}
.server-command-dialog::backdrop{background:#000a}.server-command-dialog form{display:flex;flex-direction:column;gap:14px}.server-command-dialog h2,.server-command-dialog p{margin:0}.server-command-dialog label{display:flex;flex-direction:column;gap:8px}.server-command-dialog input{box-sizing:border-box;width:100%;padding:12px;color:inherit;background:#090909;border:1px solid #333;border-radius:8px}.command-member-picker{display:flex;flex-direction:column;gap:6px;max-height:220px;overflow:auto}.command-member-picker button{text-align:left;padding:12px}.command-member-picker button[aria-pressed=true]{border-color:var(--accent,#55b3ff);background:#252525}
`;document.head.append(commandDialogStyle);

function refreshComposer(){const form=$('#server-message-form'),allowed=canSend(),commands=availableCommands().length>0;form.elements.message.disabled=!(allowed||commands);form.querySelector('button[type="submit"]').disabled=!(allowed||commands);form.elements.message.placeholder=timedOut(activeServer,user?.uid)?'You are timed out — messages are paused':allowed?'Message #'+channelLabel(activeChannel)+' · / for commands':commands?'Read-only channel · / for commands':'Read-only channel — you cannot send messages';suggestCommands()}
let lastTimeoutState=false;setInterval(()=>{if(activeServer&&user&&!$('#server-message-form').hidden){const next=timedOut(activeServer,user.uid);if(next!==lastTimeoutState){lastTimeoutState=next;refreshComposer()}}},1000);
async function serverCommand(text,confirmedTarget){
 if(!text.startsWith('/'))return false;
 const [raw,arg,duration,...extra]=text.trim().split(/\s+/),name=raw.slice(1).toLowerCase();
 if(name==='help'){if(!canUseCommand(activeServer,activeChannel,user.uid,'help'))throw Error('Commands are unavailable.');say(availableCommands().map(command=>command.usage).join(' · ')||'No moderation commands available for your role.',false);return true}
 if(!COMMANDS.some(command=>command.name===name))throw Error('Unknown command. Type / to see available commands.');
 if(!canUseCommand(activeServer,activeChannel,user.uid,name))throw Error('Your role cannot use /'+name+' in this channel.');
 if(extra.length||((name==='lock'||name==='unlock')&&arg)||(name!=='timeout'&&duration))throw Error('Usage: '+COMMANDS.find(command=>command.name===name).usage);
 if(!confirmedTarget){await openCommandDialog(name,arg,duration);return true}
 const {serverId,channel,actor}=confirmedTarget;if(user?.uid!==actor||activeServer?.id!==serverId||activeChannel!==channel)throw Error('Server or channel changed. Open the command again.');
 let target='';if(!['lock','unlock'].includes(name)){if(!arg)throw Error('Usage: '+COMMANDS.find(command=>command.name===name).usage);target=confirmedTarget.target;if(!target)throw Error('Username not found.')}
 await runTransaction(db,async transaction=>{
  if(user?.uid!==actor)throw Error('Sign in again before using commands.');
  const ref=doc(db,'servers',serverId),snapshot=await transaction.get(ref);if(!snapshot.exists())throw Error('Server no longer exists.');
  const changes=commandChanges(snapshot.data(),channel,actor,name,target,duration);
  for(const key of Object.keys(changes)){if(key.startsWith('timeouts.'))changes[key]=Timestamp.fromMillis(changes[key])}
  transaction.update(ref,{...changes,lastCommand:{name,channel,target,by:actor,at:serverTimestamp()},updatedAt:serverTimestamp()});
 });
 commandMenu.hidden=true;say('/'+name+' applied'+(target?' to '+(confirmedTarget.label||arg.replace(/^@/,'')):' to #'+channelLabel(channel))+'.',false);return true;
}
function paintAvatar(element,data){element.replaceChildren();if(data.avatarImage){const image=document.createElement('img');image.src=data.avatarImage;image.alt='';element.append(image)}else element.textContent=(data.displayName||data.username||'?')[0].toUpperCase()}
function openServerProfile(uid,data){document.dispatchEvent(new CustomEvent('simplegames:open-profile',{detail:{uid,profile:data}}))}
const roleForm=document.querySelector('#server-role-form');
const rolePreview=document.createElement('span');rolePreview.className='role-chip';rolePreview.setAttribute('aria-live','polite');roleForm?.append(rolePreview);
function previewRole(){const color=roleForm.elements.color.value;rolePreview.textContent=(roleForm.elements.name.value||'Role preview')+' '+color;rolePreview.style.color=color;rolePreview.style.borderColor=color}
roleForm?.addEventListener('input',previewRole);roleForm?.addEventListener('reset',()=>setTimeout(previewRole,0));if(roleForm)previewRole();
async function usernameUid(name){return(await findUser(db,name))?.uid||null}
async function profile(uid){if(profiles.has(uid)&&!profiles.get(uid).unavailable)return profiles.get(uid);let snap=await getDoc(doc(db,"users",uid));if(!snap.exists()&&snap.metadata.fromCache){try{snap=await getDocFromServer(doc(db,"users",uid))}catch{}}
 let data=snap.exists()?snap.data():{displayName:"Profile unavailable",unavailable:true,username:""};
 if(!snap.exists()){try{const names=await getDocs(query(collection(db,'usernames'),where('uid','==',uid),limit(1)));if(!names.empty)data={username:names.docs[0].data().username||names.docs[0].id,unavailable:true};}catch{}}
 profiles.set(uid,data);if(!profileStops.has(uid))profileStops.set(uid,onSnapshot(doc(db,"users",uid),updated=>{if(!updated.exists())return;const previous=profiles.get(uid),person=updated.data();profiles.set(uid,person);if(previous?.unavailable&&activeServer?.members?.includes(uid))renderMembers().catch(()=>{});document.querySelectorAll('[data-profile-uid]').forEach(row=>{if(row.dataset.profileUid!==uid)return;const name=row.querySelector('strong');if(name)name.textContent=person.displayName||person.username||"Member";paintAvatar(row.firstElementChild,person)});},error=>console.warn("Member profile could not refresh:",error)));return data}
function closeDialogs(){document.querySelectorAll(".server-dialog").forEach(dialog=>dialog.hidden=true)}
function appendMessageTools(row,data){
  const tools=document.createElement('div');tools.className='message-tools';
  if(data.senderId===user.uid&&ownPermission('editOwnMessages')){const edit=document.createElement('button');edit.className='message-tool';edit.textContent='Edit';edit.onclick=()=>{
    if(row.querySelector('.server-message-editor'))return;
    const editor=document.createElement('form');editor.className='server-message-editor';const field=document.createElement('textarea');field.value=data.text;field.maxLength=500;field.required=true;field.setAttribute('aria-label','Edit message');
    const save=document.createElement('button');save.type='submit';save.className='secondary-button';save.textContent='Save';const cancel=document.createElement('button');cancel.type='button';cancel.className='secondary-button';cancel.textContent='Cancel';
    const feedback=document.createElement('p');feedback.setAttribute('aria-live','polite');const original=row.querySelector('p');original.hidden=true;edit.disabled=true;
    function close(){editor.remove();original.hidden=false;edit.disabled=false}
    cancel.onclick=close;field.onkeydown=event=>{if(event.key==='Escape'){event.stopPropagation();close()}};
    editor.onsubmit=async event=>{event.preventDefault();const text=field.value.trim();if(!text){feedback.textContent='Enter a message.';return}save.disabled=true;cancel.disabled=true;try{await updateDoc(data._ref,{text,editedAt:serverTimestamp()});close()}catch(error){feedback.textContent=error.code==='permission-denied'?'Editing was blocked. Publish the latest Firestore rules and check channel permissions.':error.message;save.disabled=false;cancel.disabled=false}};
    editor.append(field,save,cancel,feedback);row.lastElementChild.append(editor);field.focus();field.setSelectionRange(field.value.length,field.value.length);
  };tools.append(edit)}
  if(data.senderId===user.uid&&ownPermission('deleteOwnMessages')||serverPermission('manageMessages')){const remove=document.createElement('button');remove.className='message-tool';remove.textContent='Delete';remove.onclick=()=>{
    if(row.querySelector('.server-delete-confirm'))return;
    const box=document.createElement('div');box.className='server-delete-confirm';const label=document.createElement('span');label.textContent='Delete this message?';
    const yes=document.createElement('button');yes.className='secondary-button';yes.textContent='Delete';const no=document.createElement('button');no.className='secondary-button';no.textContent='Cancel';const feedback=document.createElement('p');feedback.setAttribute('aria-live','polite');remove.disabled=true;
    no.onclick=()=>{box.remove();remove.disabled=false};yes.onclick=async()=>{yes.disabled=true;no.disabled=true;try{await deleteDoc(data._ref);row.remove()}catch(error){feedback.textContent=error.code==='permission-denied'?'Deletion was blocked. Check the latest rules and your role permissions.':error.message;yes.disabled=false;no.disabled=false}};
    box.append(label,yes,no,feedback);row.lastElementChild.append(box);no.focus();
  };tools.append(remove)}
  if(data.editedAt){const label=document.createElement('small');label.textContent='edited';tools.append(label)}row.lastElementChild.append(tools);
}
function editChannel(name){
  if(activeServer.ownerUid!==user.uid)return;
  const dialog=document.createElement('div');dialog.className='server-dialog';const card=document.createElement('div');card.className='server-dialog-card channel-editor';const heading=document.createElement('h3');heading.textContent='Edit channel';
  const serverId=activeServer.id,rename=document.createElement('input');rename.value=channelLabel(name);rename.maxLength=32;rename.setAttribute('aria-label','Channel name');
  const nameLabel=document.createElement('label');nameLabel.append('Channel name',rename);
  const lock=document.createElement('input');lock.type='checkbox';lock.checked=!!activeServer.channelSettings?.[name]?.locked;const label=document.createElement('label');label.className='editor-check';label.append(lock,' Lock channel (moderators can still send)');
  const permissions=channelEditor(activeServer,name,card,profiles);
  const save=document.createElement('button');save.className='submit-button';save.textContent='Save channel';save.onclick=async()=>{const title=rename.value.trim().toLowerCase().replace(/[^a-z0-9-]/g,'-').replace(/-+/g,'-').replace(/^-|-$/g,'');if(!title)return say('Enter a channel name.');if(activeServer.channels.some(id=>id!==name&&channelLabel(id)===title))return say('A channel already has that name.');save.disabled=true;try{await updateDoc(doc(db,'servers',serverId),{[`channelNames.${name}`]:title,[`channelSettings.${name}`]:{...activeServer.channelSettings?.[name],locked:lock.checked,...permissions()},updatedAt:serverTimestamp()});activeServer.channelSettings??={};activeServer.channelSettings[name]={...activeServer.channelSettings[name],locked:lock.checked,...permissions()};activeServer.channelNames??={};activeServer.channelNames[name]=title;dialog.remove();selectServer(serverId,false);say('Channel saved. Owner access is always retained.',false)}catch(error){save.disabled=false;say(error.code==='permission-denied'?'Channel save denied. Publish the complete latest firestore.rules file.':error.message)}};
  const remove=document.createElement('button');remove.className='secondary-button';remove.textContent='Delete channel';remove.style.color='#ff8585';const confirmation=document.createElement('div');confirmation.hidden=true;const warning=document.createElement('p');warning.textContent='Remove this channel from the server? Its old messages remain stored but will no longer be accessible.';const yes=document.createElement('button');yes.className='secondary-button';yes.textContent='Delete channel';const no=document.createElement('button');no.className='secondary-button';no.textContent='Keep channel';no.onclick=()=>confirmation.hidden=true;remove.onclick=()=>{confirmation.hidden=false;no.focus()};yes.onclick=async()=>{if(activeServer.id!==serverId)return;if(activeServer.channels.length<=1)return say('Keep at least one channel in the server.');yes.disabled=true;try{await updateDoc(doc(db,'servers',serverId),{channels:arrayRemove(name),updatedAt:serverTimestamp()});dialog.remove();say('Channel removed.',false)}catch(error){yes.disabled=false;say(error.message)}};confirmation.append(warning,yes,no);
  const close=document.createElement('button');close.className='secondary-button';close.textContent='Cancel';close.onclick=()=>dialog.remove();const actions=document.createElement('div');actions.className='editor-actions';actions.append(close,save,remove);card.prepend(heading,nameLabel);card.querySelectorAll('.editor-section')[2].prepend(label);card.append(confirmation,actions);dialog.append(card);panel.append(dialog);dialog.onclick=event=>{if(event.target===dialog)dialog.remove()};rename.focus();
}
function editRolePermissions(role){
  if(activeServer.ownerUid!==user.uid||role.id==='owner')return;
  const dialog=document.createElement('div');dialog.className='server-dialog';const card=document.createElement('div');card.className='server-dialog-card';const heading=document.createElement('h3');heading.textContent=`${role.name} permissions`;card.append(heading);
  const serverId=activeServer.id,name=document.createElement('input'),color=document.createElement('input'),preview=document.createElement('span');name.value=role.name;name.maxLength=32;name.setAttribute('aria-label','Role name');color.type='color';color.value=/^#[0-9a-f]{6}$/i.test(role.color)?role.color:'#8b96a8';color.setAttribute('aria-label','Role color');preview.className='role-chip';function previewEdit(){preview.textContent=name.value||'Role preview';preview.style.color=preview.style.borderColor=color.value}name.oninput=color.oninput=previewEdit;previewEdit();card.append(name,color,preview);
  const priority=document.createElement('input');priority.type='number';priority.min='0';priority.max='1000';priority.value=String(activeServer.rolePermissions?.[role.id]?.rank||0);priority.setAttribute('aria-label','Role priority');const priorityLabel=document.createElement('label');priorityLabel.append('Role priority (0–1000; higher can moderate lower): ',priority);card.append(priorityLabel);
  const send=document.createElement('input');send.type='checkbox';send.checked=activeServer.rolePermissions?.[role.id]?.sendMessages!==false;const manage=document.createElement('input');manage.type='checkbox';manage.checked=activeServer.rolePermissions?.[role.id]?.manageMessages===true;
  const edit=document.createElement('input');edit.type='checkbox';edit.checked=activeServer.rolePermissions?.[role.id]?.editOwnMessages!==false;const remove=document.createElement('input');remove.type='checkbox';remove.checked=activeServer.rolePermissions?.[role.id]?.deleteOwnMessages!==false;const joinVoice=document.createElement('input'),speakVoice=document.createElement('input');joinVoice.type=speakVoice.type='checkbox';joinVoice.checked=activeServer.rolePermissions?.[role.id]?.joinVoice!==false;speakVoice.checked=activeServer.rolePermissions?.[role.id]?.speakVoice!==false;
  for(const [input,text]of [[joinVoice,'Join voice channels'],[speakVoice,'Speak in voice channels'],[send,'Send messages'],[edit,'Edit own messages'],[remove,'Delete own messages'],[manage,'Delete other messages / send in locked channels']]){const label=document.createElement('label');label.append(input,text);card.append(label)}
  const save=document.createElement('button');save.className='submit-button';save.textContent='Save role';save.onclick=async()=>{const title=name.value.trim();if(!title)return say('Enter a role name.');const rank=Number(priority.value);if(!Number.isInteger(rank)||rank<0||rank>1000)return say('Role priority must be a whole number from 0 to 1000.');if(activeServer?.id!==serverId)return say('Open this server again before saving.');if(activeServer.roles.some(item=>item.id!==role.id&&item.name.toLowerCase()===title.toLowerCase()))return say('Choose a unique role name.');save.disabled=true;try{await updateDoc(doc(db,'servers',serverId),{roles:activeServer.roles.map(item=>item.id===role.id?{...item,name:title,color:color.value}:item),[`rolePermissions.${role.id}`]:{rank,joinVoice:joinVoice.checked,speakVoice:speakVoice.checked,sendMessages:send.checked,editOwnMessages:edit.checked,deleteOwnMessages:remove.checked,manageMessages:manage.checked},updatedAt:serverTimestamp()});dialog.remove();renderRoles();say('Role saved.',false)}catch(error){save.disabled=false;say(error.message)}};
  const cancel=document.createElement('button');cancel.className='secondary-button';cancel.textContent='Cancel';cancel.onclick=()=>dialog.remove();card.append(save,cancel);dialog.append(card);panel.append(dialog);save.focus();
}
function showDiscover(){activeServer=null;showHangouts(null);stopMessages();listenMessages.key=null;layout.classList.add("discover-mode");$("#channel-pane").hidden=true;$("#server-discover").hidden=false;$("#server-chat-heading").hidden=true;messages.hidden=true;$("#server-message-form").hidden=true;panel.querySelector(".member-pane").hidden=true;$("#server-discover-open").classList.add("active");$("#server-my-open").classList.remove("active");renderDiscover()}
function showMine(){layout.classList.remove("discover-mode");$("#server-discover").hidden=true;panel.querySelector(".member-pane").hidden=false;$("#server-discover-open").classList.remove("active");$("#server-my-open").classList.add("active");if(myServers.length)selectServer(myServers[0].id);else{$("#channel-pane").hidden=false;messages.hidden=false;messages.innerHTML='<div class="server-empty"><h3>No servers yet</h3><p>Create one or join one from Discover.</p></div>'}}
$("#servers-open")?.addEventListener("click",()=>{panel.hidden=false;showDiscover()});$("#servers-close")?.addEventListener("click",()=>panel.hidden=true);$("#server-discover-open")?.addEventListener("click",showDiscover);$("#server-my-open")?.addEventListener("click",showMine);
$("#server-create-open")?.addEventListener("click",()=>{if(!user)return say("Log in through Account first.");$("#server-create-dialog").hidden=false});$("#server-invite-open")?.addEventListener("click",()=>$("#server-invite-dialog").hidden=false);$("#server-roles-open")?.addEventListener("click",()=>{renderRoles();$("#server-roles-dialog").hidden=false});document.querySelectorAll("[data-server-dialog-close]").forEach(button=>button.addEventListener("click",closeDialogs));
onSnapshot(query(collection(db,"servers"),where("isPublic","==",true),limit(100)),snap=>{publicServers=snap.docs.map(item=>({id:item.id,...item.data()}));renderDiscover()},error=>say(error.message));
onAuthStateChanged(auth,next=>{stopMessages();listenMessages.key=null;activeServer=null;profileStops.forEach(stop=>stop());profileStops.clear();profiles.clear();user=next;listenServerInvites(db,next);stopMine();myServers=[];renderMine();syncServerNotifications();if(!user){showDiscover();return}stopMine=onSnapshot(query(collection(db,"servers"),where("members","array-contains",user.uid)),snap=>{myServers=snap.docs.map(item=>({id:item.id,...item.data()})).sort((a,b)=>safe(a.name).localeCompare(safe(b.name)));renderMine();syncServerNotifications();if(activeServer){activeServer=myServers.find(item=>item.id===activeServer.id)||null;if(activeServer)selectServer(activeServer.id,false);else showDiscover()}},error=>say(error.message))});
function renderMine(){list.innerHTML="";if(!user)return list.innerHTML="<p>Log in to see yours.</p>";if(!myServers.length)return list.innerHTML="<p>No servers yet.</p>";myServers.forEach(server=>{const button=document.createElement("button");button.type="button";const icon=document.createElement("span"),name=document.createElement("span");icon.className="server-list-icon";serverIcon(icon,server);name.textContent=server.name;button.append(icon,name);button.classList.toggle("active",activeServer?.id===server.id);button.onclick=()=>selectServer(server.id);list.append(button)})}
function renderDiscover(){if(!discoverList)return;const mode=$("#server-sort").value,sorted=[...publicServers].sort((a,b)=>mode==="az"?safe(a.name).localeCompare(safe(b.name)):mode==="newest"?(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0):(b.members?.length||0)-(a.members?.length||0));discoverList.innerHTML="";if(!sorted.length)return discoverList.innerHTML="<p>No public servers yet. Be the first to create one.</p>";sorted.forEach(server=>{const joined=!!user&&server.members?.includes(user.uid),card=document.createElement("article");card.className="discover-card";card.innerHTML='<div class="discover-card-icon"></div><div><span class="discover-category"></span><h3></h3><p></p><small></small></div><button class="submit-button" type="button"></button>';serverIcon(card.querySelector(".discover-card-icon"),server);card.querySelector(".discover-category").textContent=server.category||"Community";card.querySelector("h3").textContent=server.name;card.querySelector("p").textContent=server.description||"A Simple Games community.";card.querySelector("small").textContent=`${server.members?.length||1} member${server.members?.length===1?"":"s"}`;const button=card.querySelector("button");button.textContent=joined?"Open":"Join";button.onclick=()=>joined?selectServer(server.id):joinServer(server);discoverList.append(card)})}
$("#server-sort")?.addEventListener("change",renderDiscover);
async function joinServer(server){if(!user)return say("Log in through Account to join.");if(server.banned?.includes(user.uid))return say("You are banned from this server.");try{await updateDoc(doc(db,"servers",server.id),{members:arrayUnion(user.uid),[`memberRoles.${user.uid}`]:"member",updatedAt:serverTimestamp()});say("Server joined.",false);setTimeout(()=>selectServer(server.id),250)}catch(error){say(error.message)}}
async function selectServer(id,reset=true){const server=myServers.find(item=>item.id===id)||publicServers.find(item=>item.id===id);if(!server||!user||!server.members?.includes(user.uid))return say("Join this server first.");activeServer=server;if(reset||!server.channels?.includes(activeChannel))activeChannel=server.channels?.[0]||"general";if(!channelAccess(activeChannel)||server.channelSettings?.[activeChannel]?.type==='voice')activeChannel=server.channels.find(name=>channelAccess(name)&&server.channelSettings?.[name]?.type!=='voice')||"";layout.classList.remove("discover-mode");$("#server-discover").hidden=true;$("#channel-pane").hidden=false;panel.querySelector(".member-pane").hidden=false;$("#server-chat-heading").hidden=false;messages.hidden=false;$("#server-message-form").hidden=false;$("#server-name").textContent=server.name;$("#channel-title").textContent=channelLabel(activeChannel);$("#server-message-form input").placeholder=`Message #${channelLabel(activeChannel)}`;const owner=server.ownerUid===user.uid;$("#channel-form").hidden=!owner;$("#server-invite-open").hidden=!owner;$("#server-roles-open").hidden=!owner;$("#server-leave").hidden=false;$("#server-leave").textContent=owner?"Delete server":"Leave server";renderMine();renderChannels();renderMembers().catch(error=>say(error.message));if(activeChannel)listenMessages();else{stopMessages();listenMessages.key=null;messages.textContent="No channels are available for your role.";$("#server-message-form").hidden=true}}
function renderChannels(){showHangouts(activeServer,editChannel);channels.innerHTML="";[...new Set(activeServer.channels||["general"])].filter(name=>channelAccess(name)&&activeServer.channelSettings?.[name]?.type!=='voice').forEach(name=>{const row=document.createElement("div");row.className="server-channel-row";const button=document.createElement("button");button.className="server-channel-name";button.type="button";button.textContent=`# ${channelLabel(name)}`;button.classList.toggle("active",name===activeChannel);button.onclick=()=>{activeChannel=name;$("#channel-title").textContent=channelLabel(name);$("#server-message-form input").placeholder=`Message #${channelLabel(name)}`;renderChannels();listenMessages()};row.append(button);if(activeServer.channelSettings?.[name]?.type==='voice'){button.textContent='🔊 '+channelLabel(name);const join=document.createElement('button');join.className='secondary-button';join.type='button';join.textContent='Join';join.onclick=()=>document.dispatchEvent(new CustomEvent('simplegames:voice-server',{detail:{serverId:activeServer.id,channel:name,label:activeServer.name+' · '+channelLabel(name)}}));row.append(join);}if(activeServer.ownerUid===user.uid){const edit=document.createElement("button");edit.type="button";edit.className="server-channel-edit";edit.textContent="⚙";edit.setAttribute("aria-label",`Edit #${channelLabel(name)}`);edit.title=`Edit #${channelLabel(name)}`;edit.onclick=()=>editChannel(name);row.append(edit)}channels.append(row)})}
async function renderMembers(){const selected=activeServer,version=++memberRenderVersion;members.replaceChildren();for(const uid of new Set(selected.members||[])){const data=await profile(uid).catch(()=>({displayName:"Profile unavailable",unavailable:true}));if(version!==memberRenderVersion||activeServer?.id!==selected.id)return;const name=data.displayName||data.username||"Member",role=(selected.roles||[]).find(item=>item.id===(selected.memberRoles?.[uid]||"member")),row=document.createElement("div");row.className="server-member";row.dataset.profileUid=uid;row.innerHTML='<button type="button" class="server-member-avatar" aria-label="View profile"></button><span><strong></strong><small></small></span>';paintAvatar(row.children[0],data);row.children[0].onclick=()=>openServerProfile(uid,data);row.querySelector("strong").textContent=name;row.querySelector("strong").style.color=role?.color||"";row.querySelector("small").textContent=role?.name||(uid===selected.ownerUid?"Owner":"Member");row.querySelector("small").style.color=role?.color||"";members.append(row)}}
function listenMessages(){refreshComposer();const key=JSON.stringify([user.uid,activeServer.id,activeChannel,activeServer.channelSettings?.[activeChannel],activeServer.memberRoles?.[user.uid],activeServer.rolePermissions]);if(listenMessages.key===key)return;stopMessages();listenMessages.key=key;let initial=true;readServerChannel(activeServer.id,activeChannel);messages.innerHTML="<p>Loading messages…</p>";stopMessages=onSnapshot(query(collection(db,"servers",activeServer.id,"messages"),where("channel","==",activeChannel)),snap=>{if(listenMessages.key!==key)return;const previousScroll=messages.scrollTop,nearBottom=messages.scrollHeight-messages.scrollTop-messages.clientHeight<100;messages.innerHTML="";const visible=snap.docs.map(item=>({...item.data(),_ref:item.ref})).sort((a,b)=>(a.createdAt?.seconds||0)-(b.createdAt?.seconds||0));if(!visible.length)messages.innerHTML=`<div class="server-empty"><h3>Welcome to #${activeChannel}</h3><p>This is the start of the channel.</p></div>`;visible.forEach(data=>{const row=document.createElement("article"),date=data.createdAt?.toDate?.();row.className="server-message";row.dataset.profileUid=data.senderId;row.innerHTML='<span class="server-message-avatar"></span><div><div class="server-message-head"><strong></strong><time></time></div><p></p></div>';row.children[0].textContent=(data.senderName||"?")[0].toUpperCase();row.children[0].role="button";row.children[0].tabIndex=0;const avatar=row.children[0];profile(data.senderId).then(person=>{paintAvatar(avatar,person);row.querySelector("strong").textContent=person.displayName||person.username||data.senderName||"Member"}).catch(()=>{});avatar.onclick=async()=>{try{openServerProfile(data.senderId,await profile(data.senderId))}catch(error){say(error.message)}};avatar.onkeydown=e=>{if(e.key==="Enter"||e.key===" ")avatar.click()};row.querySelector("strong").textContent=data.senderName||"Member";const role=activeServer.roles?.find(r=>r.id===(activeServer.memberRoles?.[data.senderId]||"member"));row.querySelector("strong").style.color=role?.color||"";row.querySelector("time").textContent=date?date.toLocaleString():"sending…";row.querySelector("p").textContent=data.text;appendMessageTools(row,data);messages.append(row)});messages.scrollTop=initial||nearBottom?messages.scrollHeight:previousScroll;initial=false},error=>say(error.message))}
$("#server-create-form")?.addEventListener("submit",async event=>{event.preventDefault();if(!user)return;const form=event.currentTarget,data=new FormData(form),names=safe(data.get("members")).split(",").map(value=>value.trim()).filter(Boolean);try{const invited=await Promise.all(names.map(usernameUid));if(invited.some(uid=>!uid))throw new Error("One or more usernames were not found.");const mine=await profile(user.uid),ref=doc(collection(db,"servers")),memberList=[user.uid],memberRoles=Object.fromEntries(memberList.map(uid=>[uid,uid===user.uid?"owner":"member"]));await setDoc(ref,{name:safe(data.get("name")).trim(),description:safe(data.get("description")).trim(),category:safe(data.get("category")),isPublic:data.get("isPublic")==="on",ownerUid:user.uid,ownerName:mine.displayName||mine.username||"Owner",members:memberList,channels:["general"],roles:[{id:"owner",name:"Owner",color:"#f0b232"},{id:"member",name:"Member",color:"#8b96a8"}],memberRoles,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});for(const uid of [...new Set(invited)]){if(uid!==user.uid)await sendServerInvite(db,{id:ref.id,name:safe(data.get('name')).trim(),members:memberList},{...mine,uid:user.uid},uid)}form.reset();form.elements.isPublic.checked=true;closeDialogs();say("Server created.",false)}catch(error){say(error.message)}});
$("#server-invite-form")?.addEventListener("submit",async event=>{event.preventDefault();const form=event.currentTarget,server=activeServer,me=user;form.querySelector('.invite-result')?.remove();try{const uid=await usernameUid(new FormData(form).get("username"));if(!uid)throw Error("Username not found.");if(server.members.includes(uid))throw Error("Already a member.");const target=await profile(uid),result=document.createElement('div');result.className='invite-result';const name=document.createElement('p');name.textContent=(target.displayName||target.username)+' · @'+target.username;const send=document.createElement('button');send.type='button';send.className='submit-button';send.textContent='Send invite';send.onclick=async()=>{send.disabled=true;try{if(user?.uid!==me.uid)throw Error('Sign in again.');const mine=await profile(me.uid);await sendServerInvite(db,server,{...mine,uid:me.uid},uid);form.reset();result.remove();closeDialogs();say('Invite sent. They can accept or decline in Friends.',false)}catch(error){send.disabled=false;say(error.message)}};result.append(name,send);form.append(result)}catch(error){say(error.message)}});
$("#channel-form")?.addEventListener("submit",async event=>{event.preventDefault();const field=event.currentTarget.elements.channel,name=field.value.trim().toLowerCase().replace(/[^a-z0-9-]/g,"-").replace(/-+/g,"-").replace(/^-|-$/g,"");if(!name)return say("Use letters, numbers, or dashes.");if(activeServer.channels.some(id=>channelLabel(id)===name))return say("That channel already exists.");const id=name+"-"+Date.now().toString(36);try{await updateDoc(doc(db,"servers",activeServer.id),{channels:arrayUnion(id),[`channelNames.${id}`]:name,updatedAt:serverTimestamp()});field.value="";activeChannel=id;say("Channel added.",false)}catch(error){say(error.message)}});
$("#server-message-form")?.addEventListener("submit",async event=>{event.preventDefault();const field=event.currentTarget.elements.message,text=field.value.trim();if(!text||!activeServer)return;field.value="";try{if(await serverCommand(text))return;if(!canSend())throw Error("This channel is locked or your role cannot send messages.");const mine=await profile(user.uid);await addDoc(collection(db,"servers",activeServer.id,"messages"),{senderId:user.uid,senderName:mine.displayName||mine.username||"Member",channel:activeChannel,text,createdAt:serverTimestamp()})}catch(error){field.value=text;say(error.message)}});
function renderRoles(){const roleList=$("#server-role-list"),memberSelect=$("#server-role-assign-form").elements.member,roleSelect=$("#server-role-assign-form").elements.role;roleList.innerHTML="";memberSelect.innerHTML="";roleSelect.innerHTML="";(activeServer.roles||[]).forEach(role=>{const chip=document.createElement("span"),option=document.createElement("option");chip.className="role-chip";chip.textContent=role.name;chip.style.borderColor=chip.style.color=role.color;roleList.append(chip);if(role.id!=="owner"){const permissions=document.createElement("button");permissions.className="secondary-button";permissions.textContent=`Edit ${role.name}`;permissions.onclick=()=>editRolePermissions(role);roleList.append(permissions)}option.value=role.id;option.textContent=role.name;roleSelect.append(option)});(activeServer.members||[]).forEach(async uid=>{const data=await profile(uid),option=document.createElement("option");option.value=uid;option.textContent=data.displayName||data.username;memberSelect.append(option)})}
$("#server-role-form")?.addEventListener("submit",async event=>{event.preventDefault();const form=event.currentTarget,data=new FormData(form),name=safe(data.get("name")).trim(),id=name.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");if(!id)return;if(["owner","member"].includes(id)||activeServer.roles?.some(role=>role.id===id))return say("Choose a unique role name.");try{await updateDoc(doc(db,"servers",activeServer.id),{roles:arrayUnion({id,name,color:safe(data.get("color"))}),updatedAt:serverTimestamp()});form.reset();say("Role created.",false);closeDialogs()}catch(error){say(error.message)}});
$("#server-role-assign-form")?.addEventListener("submit",async event=>{event.preventDefault();const data=new FormData(event.currentTarget);try{await updateDoc(doc(db,"servers",activeServer.id),{[`memberRoles.${data.get("member")}`]:data.get("role"),updatedAt:serverTimestamp()});say("Role assigned.",false);closeDialogs()}catch(error){say(error.message)}});
$("#server-leave")?.addEventListener("click",async()=>{if(!activeServer)return;if(activeServer.ownerUid===user.uid){if(!confirm("Delete this server for everyone?"))return;await deleteDoc(doc(db,"servers",activeServer.id));say("Server deleted.",false)}else{if(!confirm("Leave this server?"))return;await updateDoc(doc(db,"servers",activeServer.id),{members:arrayRemove(user.uid),updatedAt:serverTimestamp()});say("You left the server.",false)}showDiscover()});
