import { getApp, getApps, initializeApp } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js";
import { getAuth, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js";
import { addDoc, arrayRemove, arrayUnion, collection, deleteDoc, doc, getDoc, getFirestore, limit, onSnapshot, orderBy, query, serverTimestamp, setDoc, updateDoc, where } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js";
const config={apiKey:"AIzaSyDzJu7zyLTZWwffbS5wcxAGym5orePvNKg",authDomain:"simplegames-23c2c.firebaseapp.com",projectId:"simplegames-23c2c",storageBucket:"simplegames-23c2c.firebasestorage.app",messagingSenderId:"993873419513",appId:"1:993873419513:web:14e22dfff6d7f0c7051628",measurementId:"G-NC81W7MYG0"};
const app=getApps().length?getApp():initializeApp(config),auth=getAuth(app),db=getFirestore(app),$=selector=>document.querySelector(selector);
const panel=$("#server-panel"),layout=panel.querySelector(".server-layout"),list=$("#server-list"),channels=$("#channel-list"),messages=$("#server-messages"),members=$("#server-members"),status=$("#server-status"),discoverList=$("#server-discover-list");
let user=null,myServers=[],publicServers=[],activeServer=null,activeChannel="general",profiles=new Map(),stopMine=()=>{},stopMessages=()=>{};
function say(text,error=true){status.textContent=text;status.style.background=error?"#b33b46":"#237a4b";clearTimeout(say.timer);say.timer=setTimeout(()=>status.textContent="",4000)}
function safe(value){return String(value??"")}
async function usernameUid(name){const snap=await getDoc(doc(db,"usernames",safe(name).trim().toLowerCase()));return snap.exists()?snap.data().uid:null}
async function profile(uid){if(profiles.has(uid))return profiles.get(uid);const snap=await getDoc(doc(db,"users",uid)),data=snap.exists()?snap.data():{displayName:"Member",username:"member"};profiles.set(uid,data);return data}
function closeDialogs(){document.querySelectorAll(".server-dialog").forEach(dialog=>dialog.hidden=true)}
function showDiscover(){activeServer=null;stopMessages();layout.classList.add("discover-mode");$("#channel-pane").hidden=true;$("#server-discover").hidden=false;$("#server-chat-heading").hidden=true;messages.hidden=true;$("#server-message-form").hidden=true;panel.querySelector(".member-pane").hidden=true;$("#server-discover-open").classList.add("active");$("#server-my-open").classList.remove("active");renderDiscover()}
function showMine(){layout.classList.remove("discover-mode");$("#server-discover").hidden=true;panel.querySelector(".member-pane").hidden=false;$("#server-discover-open").classList.remove("active");$("#server-my-open").classList.add("active");if(myServers.length)selectServer(myServers[0].id);else{$("#channel-pane").hidden=false;messages.hidden=false;messages.innerHTML='<div class="server-empty"><h3>No servers yet</h3><p>Create one or join one from Discover.</p></div>'}}
$("#servers-open")?.addEventListener("click",()=>{panel.hidden=false;showDiscover()});$("#servers-close")?.addEventListener("click",()=>panel.hidden=true);$("#server-discover-open")?.addEventListener("click",showDiscover);$("#server-my-open")?.addEventListener("click",showMine);
$("#server-create-open")?.addEventListener("click",()=>{if(!user)return say("Log in through Account first.");$("#server-create-dialog").hidden=false});$("#server-invite-open")?.addEventListener("click",()=>$("#server-invite-dialog").hidden=false);$("#server-roles-open")?.addEventListener("click",()=>{renderRoles();$("#server-roles-dialog").hidden=false});document.querySelectorAll("[data-server-dialog-close]").forEach(button=>button.addEventListener("click",closeDialogs));
onSnapshot(query(collection(db,"servers"),where("isPublic","==",true),limit(100)),snap=>{publicServers=snap.docs.map(item=>({id:item.id,...item.data()}));renderDiscover()},error=>say(error.message));
onAuthStateChanged(auth,next=>{user=next;stopMine();myServers=[];renderMine();if(!user){renderDiscover();return}stopMine=onSnapshot(query(collection(db,"servers"),where("members","array-contains",user.uid)),snap=>{myServers=snap.docs.map(item=>({id:item.id,...item.data()})).sort((a,b)=>safe(a.name).localeCompare(safe(b.name)));renderMine();if(activeServer){activeServer=myServers.find(item=>item.id===activeServer.id)||null;if(activeServer)selectServer(activeServer.id,false)}},error=>say(error.message))});
function renderMine(){list.innerHTML="";if(!user)return list.innerHTML="<p>Log in to see yours.</p>";if(!myServers.length)return list.innerHTML="<p>No servers yet.</p>";myServers.forEach(server=>{const button=document.createElement("button");button.type="button";button.textContent=server.name;button.classList.toggle("active",activeServer?.id===server.id);button.onclick=()=>selectServer(server.id);list.append(button)})}
function renderDiscover(){if(!discoverList)return;const mode=$("#server-sort").value,sorted=[...publicServers].sort((a,b)=>mode==="az"?safe(a.name).localeCompare(safe(b.name)):mode==="newest"?(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0):(b.members?.length||0)-(a.members?.length||0));discoverList.innerHTML="";if(!sorted.length)return discoverList.innerHTML="<p>No public servers yet. Be the first to create one.</p>";sorted.forEach(server=>{const joined=!!user&&server.members?.includes(user.uid),card=document.createElement("article");card.className="discover-card";card.innerHTML='<div class="discover-card-icon"></div><div><span class="discover-category"></span><h3></h3><p></p><small></small></div><button class="submit-button" type="button"></button>';card.querySelector(".discover-card-icon").textContent=server.name?.[0]?.toUpperCase()||"S";card.querySelector(".discover-category").textContent=server.category||"Community";card.querySelector("h3").textContent=server.name;card.querySelector("p").textContent=server.description||"A Simple Games community.";card.querySelector("small").textContent=`${server.members?.length||1} member${server.members?.length===1?"":"s"}`;const button=card.querySelector("button");button.textContent=joined?"Open":"Join";button.onclick=()=>joined?selectServer(server.id):joinServer(server);discoverList.append(card)})}
$("#server-sort")?.addEventListener("change",renderDiscover);
async function joinServer(server){if(!user)return say("Log in through Account to join.");try{await updateDoc(doc(db,"servers",server.id),{members:arrayUnion(user.uid),[`memberRoles.${user.uid}`]:"member",updatedAt:serverTimestamp()});say("Server joined.",false);setTimeout(()=>selectServer(server.id),250)}catch(error){say(error.message)}}
async function selectServer(id,reset=true){const server=myServers.find(item=>item.id===id)||publicServers.find(item=>item.id===id);if(!server||!user||!server.members?.includes(user.uid))return say("Join this server first.");activeServer=server;if(reset||!server.channels?.includes(activeChannel))activeChannel=server.channels?.[0]||"general";layout.classList.remove("discover-mode");$("#server-discover").hidden=true;$("#channel-pane").hidden=false;panel.querySelector(".member-pane").hidden=false;$("#server-chat-heading").hidden=false;messages.hidden=false;$("#server-message-form").hidden=false;$("#server-name").textContent=server.name;$("#channel-title").textContent=activeChannel;$("#server-message-form input").placeholder=`Message #${activeChannel}`;const owner=server.ownerUid===user.uid;$("#channel-form").hidden=!owner;$("#server-invite-open").hidden=!owner;$("#server-roles-open").hidden=!owner;$("#server-leave").hidden=false;renderMine();renderChannels();await renderMembers();listenMessages()}
function renderChannels(){channels.innerHTML="";(activeServer.channels||["general"]).forEach(name=>{const button=document.createElement("button");button.type="button";button.textContent=`# ${name}`;button.classList.toggle("active",name===activeChannel);button.onclick=()=>{activeChannel=name;$("#channel-title").textContent=name;$("#server-message-form input").placeholder=`Message #${name}`;renderChannels();listenMessages()};channels.append(button)})}
async function renderMembers(){members.innerHTML="";for(const uid of activeServer.members||[]){const data=await profile(uid),name=data.displayName||data.username||"Member",role=(activeServer.roles||[]).find(item=>item.id===(activeServer.memberRoles?.[uid]||"member")),row=document.createElement("div");row.className="server-member";row.innerHTML='<span class="server-member-avatar"></span><span><strong></strong><small></small></span>';row.children[0].textContent=name[0]?.toUpperCase()||"?";row.querySelector("strong").textContent=name;row.querySelector("small").textContent=role?.name||(uid===activeServer.ownerUid?"Owner":"Member");row.querySelector("small").style.color=role?.color||"";members.append(row)}}
function listenMessages(){stopMessages();messages.innerHTML="<p>Loading messages…</p>";stopMessages=onSnapshot(query(collection(db,"servers",activeServer.id,"messages"),orderBy("createdAt","asc"),limit(150)),snap=>{messages.innerHTML="";const visible=snap.docs.map(item=>item.data()).filter(item=>item.channel===activeChannel);if(!visible.length)messages.innerHTML=`<div class="server-empty"><h3>Welcome to #${activeChannel}</h3><p>This is the start of the channel.</p></div>`;visible.forEach(data=>{const row=document.createElement("article"),date=data.createdAt?.toDate?.();row.className="server-message";row.innerHTML='<span class="server-message-avatar"></span><div><div class="server-message-head"><strong></strong><time></time></div><p></p></div>';row.children[0].textContent=(data.senderName||"?")[0].toUpperCase();row.querySelector("strong").textContent=data.senderName||"Member";row.querySelector("time").textContent=date?date.toLocaleString():"sending…";row.querySelector("p").textContent=data.text;messages.append(row)});messages.scrollTop=messages.scrollHeight},error=>say(error.message))}
$("#server-create-form")?.addEventListener("submit",async event=>{event.preventDefault();if(!user)return;const data=new FormData(event.currentTarget),names=safe(data.get("members")).split(",").map(value=>value.trim()).filter(Boolean);try{const invited=await Promise.all(names.map(usernameUid));if(invited.some(uid=>!uid))throw new Error("One or more usernames were not found.");const mine=await profile(user.uid),ref=doc(collection(db,"servers")),memberList=[...new Set([user.uid,...invited])],memberRoles=Object.fromEntries(memberList.map(uid=>[uid,uid===user.uid?"owner":"member"]));await setDoc(ref,{name:safe(data.get("name")).trim(),description:safe(data.get("description")).trim(),category:safe(data.get("category")),isPublic:data.get("isPublic")==="on",ownerUid:user.uid,ownerName:mine.displayName||mine.username||"Owner",members:memberList,channels:["general"],roles:[{id:"owner",name:"Owner",color:"#f0b232"},{id:"member",name:"Member",color:"#8b96a8"}],memberRoles,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});event.currentTarget.reset();event.currentTarget.elements.isPublic.checked=true;closeDialogs();say("Server created.",false)}catch(error){say(error.message)}});
$("#server-invite-form")?.addEventListener("submit",async event=>{event.preventDefault();try{const uid=await usernameUid(new FormData(event.currentTarget).get("username"));if(!uid)throw new Error("Username not found.");await updateDoc(doc(db,"servers",activeServer.id),{members:arrayUnion(uid),[`memberRoles.${uid}`]:"member",updatedAt:serverTimestamp()});event.currentTarget.reset();closeDialogs();say("Member added.",false)}catch(error){say(error.message)}});
$("#channel-form")?.addEventListener("submit",async event=>{event.preventDefault();const field=event.currentTarget.elements.channel,name=field.value.trim().toLowerCase().replace(/[^a-z0-9-]/g,"-").replace(/-+/g,"-").replace(/^-|-$/g,"");if(!name)return say("Use letters, numbers, or dashes.");try{await updateDoc(doc(db,"servers",activeServer.id),{channels:arrayUnion(name),updatedAt:serverTimestamp()});field.value="";activeChannel=name;say("Channel added.",false)}catch(error){say(error.message)}});
$("#server-message-form")?.addEventListener("submit",async event=>{event.preventDefault();const field=event.currentTarget.elements.message,text=field.value.trim();if(!text||!activeServer)return;field.value="";try{const mine=await profile(user.uid);await addDoc(collection(db,"servers",activeServer.id,"messages"),{senderId:user.uid,senderName:mine.displayName||mine.username||"Member",channel:activeChannel,text,createdAt:serverTimestamp()})}catch(error){field.value=text;say(error.message)}});
function renderRoles(){const roleList=$("#server-role-list"),memberSelect=$("#server-role-assign-form").elements.member,roleSelect=$("#server-role-assign-form").elements.role;roleList.innerHTML="";memberSelect.innerHTML="";roleSelect.innerHTML="";(activeServer.roles||[]).forEach(role=>{const chip=document.createElement("span"),option=document.createElement("option");chip.className="role-chip";chip.textContent=role.name;chip.style.borderColor=chip.style.color=role.color;roleList.append(chip);option.value=role.id;option.textContent=role.name;roleSelect.append(option)});(activeServer.members||[]).forEach(async uid=>{const data=await profile(uid),option=document.createElement("option");option.value=uid;option.textContent=data.displayName||data.username;memberSelect.append(option)})}
$("#server-role-form")?.addEventListener("submit",async event=>{event.preventDefault();const data=new FormData(event.currentTarget),name=safe(data.get("name")).trim(),id=name.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");if(!id)return;try{await updateDoc(doc(db,"servers",activeServer.id),{roles:arrayUnion({id,name,color:safe(data.get("color"))}),updatedAt:serverTimestamp()});event.currentTarget.reset();say("Role created.",false);closeDialogs()}catch(error){say(error.message)}});
$("#server-role-assign-form")?.addEventListener("submit",async event=>{event.preventDefault();const data=new FormData(event.currentTarget);try{await updateDoc(doc(db,"servers",activeServer.id),{[`memberRoles.${data.get("member")}`]:data.get("role"),updatedAt:serverTimestamp()});say("Role assigned.",false);closeDialogs()}catch(error){say(error.message)}});
$("#server-leave")?.addEventListener("click",async()=>{if(!activeServer)return;if(activeServer.ownerUid===user.uid){if(!confirm("Delete this server for everyone?"))return;await deleteDoc(doc(db,"servers",activeServer.id));say("Server deleted.",false)}else{if(!confirm("Leave this server?"))return;await updateDoc(doc(db,"servers",activeServer.id),{members:arrayRemove(user.uid),updatedAt:serverTimestamp()});say("You left the server.",false)}showDiscover()});
