import{initializeApp}from"https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js";
import{createUserWithEmailAndPassword,deleteUser,getAuth,onAuthStateChanged,sendPasswordResetEmail,signInWithEmailAndPassword,signOut,updatePassword}from"https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js";
import{addDoc,collection,deleteDoc,doc,FieldPath,getDoc,getFirestore,increment,limit,onSnapshot,orderBy,query,runTransaction,serverTimestamp,setDoc,updateDoc,where,writeBatch}from"https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js";
const app=initializeApp({apiKey:"AIzaSyDzJu7zyLTZWwffbS5wcxAGym5orePvNKg",authDomain:"simplegames-23c2c.firebaseapp.com",projectId:"simplegames-23c2c",storageBucket:"simplegames-23c2c.firebasestorage.app",messagingSenderId:"993873419513",appId:"1:993873419513:web:14e22dfff6d7f0c7051628",measurementId:"G-NC81W7MYG0"});
const auth=getAuth(app),db=getFirestore(app),$=s=>document.querySelector(s),panel=$("#social-panel"),authView=$("#auth-view"),socialView=$("#social-view"),status=$("#social-status");
let profile,activeFriend,activeGroup,friends=[],groups=new Map(),chats=new Map(),friendProfiles=new Map(),presenceTimer=0,typingTimer=0,chatsReady=false,groupsReady=false,friendFilter="",profileLinkUsername="",profileLinkOpened=false,replyTo=null,attachmentData=null,pendingAvatarImage=null;
let stopProfile=()=>{},stopRequests=()=>{},stopFriends=()=>{},stopChats=()=>{},stopGroups=()=>{},stopMessages=()=>{},stopBlocks=()=>{},stopLeaderboard=()=>{},stopFriendProfiles=[];
function openGroup(group){activeFriend=null;activeGroup=group;setReply(null);showView("friends");$("#chat-title").textContent=`👥 ${group.name}`;$("#chat-actions").hidden=false;document.querySelectorAll(".dm-action").forEach(x=>x.hidden=true);document.querySelectorAll(".group-action").forEach(x=>x.hidden=false);$("#message-form").hidden=false;$("#typing-status").textContent="";markGroupRead(group.id);stopMessages();stopMessages=onSnapshot(query(collection(db,"groupChats",group.id,"messages"),orderBy("createdAt","asc"),limit(100)),snap=>{const list=$("#message-list");list.replaceChildren();if(snap.empty)list.append(Object.assign(document.createElement("p"),{textContent:"No messages yet. Say hi!"}));snap.forEach(x=>list.append(renderMessage(x,"Member")));list.scrollTop=list.scrollHeight;markGroupRead(group.id)},e=>showStatus(friendlyError(e),true))}
function showStatus(m="",error=false){status.textContent=m;status.style.color=error?"#ff8585":"#ffcb65"}
function friendlyError(e){return({"auth/email-already-in-use":"That email already has an account.","auth/invalid-credential":"The email or password is incorrect.","auth/invalid-email":"Enter a valid email address.","auth/requires-recent-login":"Log out and back in before changing your password.","auth/too-many-requests":"Too many attempts. Wait a bit and try again.","auth/weak-password":"The password must contain at least 6 characters."})[e.code]||e.message||"Something went wrong."}
function badgeFor(){return""}
function applyAvatar(element,data={}){const image=data.avatarImage||"";element.classList.toggle("has-image",!!image);image?element.style.setProperty("--avatar-image",`url("${image.replaceAll('"','%22')}")`):element.style.removeProperty("--avatar-image");element.style.setProperty("--avatar-fallback",`"${(data.displayName||data.username||"?").charAt(0).toUpperCase()}"`)}
function messageSound(){if(!profile||profile.messageSound===false||profile.doNotDisturb)return;try{const C=window.AudioContext||window.webkitAudioContext,c=new C(),o=c.createOscillator(),g=c.createGain();o.frequency.value=660;g.gain.setValueAtTime(.05,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.18);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.18)}catch{}}
$("#account-open").onclick=()=>{panel.hidden=false;showStatus()};$("#social-close").onclick=()=>panel.hidden=true;panel.onclick=e=>{if(e.target===panel)panel.hidden=true};document.addEventListener("keydown",e=>{if(e.key==="Escape")panel.hidden=true});
function showAuth(mode){$("#login-form").hidden=mode!=="login";$("#signup-form").hidden=mode!=="signup";$("#login-tab").setAttribute("aria-pressed",mode==="login");$("#signup-tab").setAttribute("aria-pressed",mode==="signup");showStatus()}
$("#login-tab").onclick=()=>showAuth("login");$("#signup-tab").onclick=()=>showAuth("signup");showAuth("login");
async function reset(email){if(!email)return showStatus("Enter your email address first.",true);try{await sendPasswordResetEmail(auth,email);showStatus("Password reset email sent. Check your inbox.")}catch(e){showStatus(friendlyError(e),true)}}
$("#forgot-password").onclick=()=>reset($("#login-form").elements.email.value.trim());$("#send-reset").onclick=()=>reset(auth.currentUser?.email);
$("#signup-form").onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,d=new FormData(f),username=String(d.get("username")).trim(),usernameLower=username.toLowerCase(),email=String(d.get("email")).trim(),password=String(d.get("password"));if(!/^[A-Za-z0-9_]{3,20}$/.test(username))return showStatus("Username must be 3–20 letters, numbers, or underscores.",true);let cred,created=false;try{cred=await createUserWithEmailAndPassword(auth,email,password);await runTransaction(db,async t=>{const ur=doc(db,"usernames",usernameLower),ud=await t.get(ur);if(ud.exists()&&(await t.get(doc(db,"users",ud.data().uid))).exists())throw Error("That username is already taken.");t.set(ur,{uid:cred.user.uid,username});t.set(doc(db,"users",cred.user.uid),{username,usernameLower,displayName:username,avatar:"🙂",bio:"",status:"online",lastActive:serverTimestamp(),currentGame:null,createdAt:serverTimestamp()})});created=true;f.reset();showStatus("Account created.")}catch(err){if(cred?.user&&!created)await deleteUser(cred.user).catch(()=>{});showStatus(friendlyError(err),true)}};
$("#login-form").onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,d=new FormData(f);try{showStatus("Logging in…");await signInWithEmailAndPassword(auth,String(d.get("email")).trim(),String(d.get("password")));f.reset();showStatus()}catch(err){showStatus(friendlyError(err),true)}};
$("#password-form").onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;try{await updatePassword(auth.currentUser,String(new FormData(f).get("password")));f.reset();showStatus("Password changed.")}catch(err){showStatus(friendlyError(err),true)}};
const pairId=(a,b)=>[a,b].sort().join("_");
function button(text,handler){const b=document.createElement("button");b.className="secondary-button";b.type="button";b.textContent=text;b.onclick=handler;return b}
function row(name,actions=[]){const r=document.createElement("div");r.className="social-list-item";const s=document.createElement("span");s.textContent=name;r.append(s,...actions);return r}
function setReply(data){replyTo=data?{text:(data.text||"Image").slice(0,100),senderName:data.senderName||"Friend"}:null;$("#reply-preview").hidden=!replyTo;$("#reply-preview-text").textContent=replyTo?`Replying to ${replyTo.senderName}: ${replyTo.text}`:"";$("#message-form").elements.message.focus()}
$("#reply-cancel").onclick=()=>setReply(null);
$("#message-attachment").onchange=async e=>{const file=e.target.files?.[0];attachmentData=null;if(!file)return;if(!file.type.startsWith("image/"))return showStatus("Choose an image or GIF.",true);if(file.size>180*1024){e.target.value="";return showStatus("Images and GIFs must be 180 KB or smaller.",true)}const reader=new FileReader();reader.onload=()=>{attachmentData={dataUrl:reader.result,type:file.type,name:file.name.slice(0,80)};showStatus(`${file.name} attached.`)};reader.readAsDataURL(file)};
function renderMessage(messageDoc,senderFallback="Friend"){const d=messageDoc.data(),bubble=document.createElement("div"),text=document.createElement("span"),time=document.createElement("small"),stamp=d.createdAt?.toDate?d.createdAt.toDate().toLocaleString():"Sending…",mine=d.senderId===auth.currentUser.uid;bubble.className=`message${mine?" mine":""}`;if(d.reply){const quote=document.createElement("span");quote.className="message-quote";quote.textContent=`${d.reply.senderName}: ${d.reply.text}`;bubble.append(quote)}if(d.senderName){const sender=document.createElement("small");sender.textContent=d.senderName;bubble.append(sender)}if(d.text){text.textContent=d.text;bubble.append(text)}if(d.attachment?.dataUrl){const image=document.createElement("img");image.className="message-image";image.src=d.attachment.dataUrl;image.alt=d.attachment.name||"Shared image";bubble.append(image)}time.textContent=`${stamp}${d.editedAt?" · Edited":""}`;time.dataset.time=stamp;time.dataset.sent=ms(d.createdAt);bubble.append(time);const reactions=document.createElement("div");reactions.className="reaction-bar";for(const emoji of["👍","❤️","😂"]){const count=Object.values(d.reactions||{}).filter(v=>v===emoji).length,r=button(`${emoji}${count?` ${count}`:""}`,()=>updateDoc(messageDoc.ref,new FieldPath("reactions",auth.currentUser.uid),d.reactions?.[auth.currentUser.uid]===emoji?null:emoji).catch(err=>showStatus(friendlyError(err),true)));r.className=`reaction-button${d.reactions?.[auth.currentUser.uid]===emoji?" mine-reaction":""}`;reactions.append(r)}bubble.append(reactions);const tools=document.createElement("div");tools.className="message-tools";const reply=button("Reply",()=>setReply({...d,senderName:d.senderName||(mine?(profile.displayName||profile.username):senderFallback)}));reply.className="message-tool";tools.append(reply);if(mine){const edit=button("Edit",async()=>{const changed=prompt("Edit your message:",d.text||"");if(changed===null||(!changed.trim()&&!d.attachment))return;await updateDoc(messageDoc.ref,{text:changed.trim().slice(0,500),editedAt:serverTimestamp()}).catch(err=>showStatus(friendlyError(err),true))}),remove=button("Delete",()=>deleteDoc(messageDoc.ref).catch(err=>showStatus(friendlyError(err),true)));edit.className=remove.className="message-tool";tools.append(edit,remove)}bubble.append(tools);return bubble}
const ms=t=>t?.toMillis?t.toMillis():0,isOnline=d=>!d?.hideOnline&&d?.status==="online"&&Date.now()-ms(d.lastActive)<180000;
function activity(d){if(d?.hideOnline)return"Activity private";if(isOnline(d))return d.doNotDisturb?"Do Not Disturb":(!d.privateActivity&&d.currentGame?.title?`Playing ${d.currentGame.title}`:"Online now");const t=ms(d?.lastActive);if(!t)return"Offline";const when=new Date(t),today=new Date(),sameDay=when.toDateString()===today.toDateString(),yesterday=new Date(today);yesterday.setDate(today.getDate()-1);const day=sameDay?"today":when.toDateString()===yesterday.toDateString()?"yesterday":when.toLocaleDateString();return`Last active ${day} at ${when.toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}`}
function unread(uid){const c=chats.get(pairId(auth.currentUser.uid,uid));if(!c||c.lastSenderId===auth.currentUser.uid)return 0;return c.unreadCounts?.[auth.currentUser.uid]??(ms(c.updatedAt)>ms(c.readAt?.[auth.currentUser.uid])?1:0)}
function renderFriends(){const list=$("#friend-list"),pinned=profile?.pinnedFriends||[];list.replaceChildren();const shown=friends.filter(f=>{const d=friendProfiles.get(f.uid)||f;return`${d.displayName||""} ${d.username||""}`.toLowerCase().includes(friendFilter)}).sort((a,b)=>Number(pinned.includes(b.uid))-Number(pinned.includes(a.uid)));if(!shown.length)list.append(Object.assign(document.createElement("p"),{textContent:friends.length?"No matching friends":"No friends yet"}));shown.forEach(f=>{const d=friendProfiles.get(f.uid)||f,b=button("",()=>openChat({...f,username:d.username||f.username}));b.classList.add("friend-button");const main=document.createElement("span"),dot=document.createElement("span"),avatar=document.createElement("span"),copy=document.createElement("span"),name=document.createElement("strong"),act=document.createElement("small"),earned=badgeFor(d);main.className="friend-main";dot.className=`presence-dot${isOnline(d)?" online":""}`;avatar.className="profile-avatar friend-avatar";applyAvatar(avatar,d);copy.className="friend-copy";name.textContent=`${pinned.includes(f.uid)?"📌 ":""}${d.displayName||d.username||"Friend"}${earned?` ${earned}`:""}`;act.textContent=`${d.statusText?`${d.statusText} · `:""}${activity(d)}`;copy.append(name,act);main.append(dot,avatar,copy);b.append(main);const view=button("Profile",()=>showFriendProfile(f.uid));view.classList.add("friend-profile-button");const r=row("",[b,view]),n=unread(f.uid);if(n){const badge=document.createElement("span");badge.className="friend-unread";badge.textContent=n;r.append(badge)}list.append(r)});const count=friends.reduce((n,f)=>n+unread(f.uid),0),badge=$("#account-unread");badge.textContent=count;badge.hidden=!count}
$("#friend-filter").oninput=e=>{friendFilter=e.target.value.trim().toLowerCase();renderFriends()};
function listenRequests(uid){stopRequests();stopRequests=onSnapshot(query(collection(db,"friendRequests"),where("toUid","==",uid)),async snap=>{const list=$("#request-list");list.replaceChildren();const pending=snap.docs.filter(x=>x.data().status==="pending");if(!pending.length)return list.append(Object.assign(document.createElement("p"),{textContent:"No requests"}));for(const req of pending){const d=req.data(),u=await getDoc(doc(db,"users",d.fromUid)),name=u.data()?.username||"Unknown user";const accept=button("Accept",async()=>{const batch=writeBatch(db);batch.update(req.ref,{status:"accepted",respondedAt:serverTimestamp()});batch.set(doc(db,"friendships",pairId(uid,d.fromUid)),{members:[uid,d.fromUid],createdAt:serverTimestamp()});await batch.commit().catch(err=>showStatus(friendlyError(err),true))}),decline=button("Decline",()=>updateDoc(req.ref,{status:"declined",respondedAt:serverTimestamp()}));list.append(row(name,[accept,decline]))}},e=>showStatus(friendlyError(e),true))}
function listenFriends(uid){stopFriends();stopFriends=onSnapshot(query(collection(db,"friendships"),where("members","array-contains",uid)),snap=>{stopFriendProfiles.forEach(s=>s());stopFriendProfiles=[];friends=snap.docs.map(x=>({uid:x.data().members.find(m=>m!==uid),friendshipId:x.id}));friendProfiles.clear();renderFriends();friends.forEach(f=>stopFriendProfiles.push(onSnapshot(doc(db,"users",f.uid),u=>{if(!u.exists())return;friendProfiles.set(f.uid,u.data());f.username=u.data().username;renderFriends();if(activeFriend?.uid===f.uid)$("#chat-title").textContent=`${u.data().avatar||"🙂"} ${u.data().displayName||u.data().username}`})))},e=>showStatus(friendlyError(e),true))}
function listenChats(uid){stopChats();stopChats=onSnapshot(query(collection(db,"chats"),where("members","array-contains",uid)),snap=>{const next=new Map(snap.docs.map(x=>[x.id,x.data()]));if(chatsReady){for(const[id,data]of next){const before=chats.get(id);if(data.lastSenderId!==uid&&(data.unreadCounts?.[uid]||0)>(before?.unreadCounts?.[uid]||0))messageSound()}}chats=next;chatsReady=true;renderFriends();updateAccountUnread();updateChatSignals()},e=>showStatus(friendlyError(e),true))}
function groupUnread(d){return d.lastSenderId!==auth.currentUser?.uid?(d.unreadCounts?.[auth.currentUser?.uid]||0):0}
function updateAccountUnread(){if(!auth.currentUser)return;const total=friends.reduce((n,f)=>n+unread(f.uid),0)+[...groups.values()].reduce((n,g)=>n+groupUnread(g),0),badge=$("#account-unread");badge.textContent=total;badge.hidden=!total}
async function markGroupRead(id){try{await updateDoc(doc(db,"groupChats",id),new FieldPath("unreadCounts",auth.currentUser.uid),0)}catch{}}
function renderGroups(){const list=$("#group-list"),items=[...groups.entries()].sort((a,b)=>ms(b[1].updatedAt)-ms(a[1].updatedAt));list.replaceChildren();if(!items.length)list.append(Object.assign(document.createElement("p"),{textContent:"No groups yet"}));for(const[id,d]of items){const open=button(`👥 ${d.name}`,()=>openGroup({id,...d}));open.classList.add("friend-button");const r=row("",[open]),count=groupUnread(d);if(count){const badge=document.createElement("span");badge.className="friend-unread";badge.textContent=count;r.append(badge)}list.append(r)}updateAccountUnread()}
function listenGroups(uid){stopGroups();stopGroups=onSnapshot(query(collection(db,"groupChats"),where("members","array-contains",uid)),snap=>{const next=new Map(snap.docs.map(x=>[x.id,x.data()]));if(groupsReady){for(const[id,d]of next){const before=groups.get(id);if(d.lastSenderId!==uid&&(d.unreadCounts?.[uid]||0)>(before?.unreadCounts?.[uid]||0))messageSound()}}groups=next;if(activeGroup&&next.has(activeGroup.id)){activeGroup={id:activeGroup.id,...next.get(activeGroup.id)};$("#chat-title").textContent=`👥 ${activeGroup.name}`;if(!$("#group-manager-view").hidden)renderGroupManager()}groupsReady=true;renderGroups()},e=>showStatus(friendlyError(e),true))}
$("#group-form").onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,data=new FormData(f),name=String(data.get("name")).trim(),names=[...new Set(String(data.get("members")).split(",").map(x=>x.trim().toLowerCase()).filter(Boolean))];if(!name||!names.length)return;if(names.length>7)return showStatus("Groups can include up to 8 people total.",true);try{const members=[auth.currentUser.uid];for(const username of names){const match=await getDoc(doc(db,"usernames",username));if(!match.exists())throw Error(`No user named ${username}.`);const uid=match.data().uid;if(uid===auth.currentUser.uid)continue;if(!(await getDoc(doc(db,"friendships",pairId(auth.currentUser.uid,uid)))).exists())throw Error(`${match.data().username} is not your friend yet.`);members.push(uid)}if(members.length<2)throw Error("Add at least one friend.");await addDoc(collection(db,"groupChats"),{name,ownerUid:auth.currentUser.uid,members:[...new Set(members)],createdAt:serverTimestamp(),updatedAt:serverTimestamp()});f.reset();showStatus("Group created.")}catch(err){showStatus(friendlyError(err),true)}};
$("#friend-search").onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,name=String(new FormData(f).get("username")).trim().toLowerCase();try{const match=await getDoc(doc(db,"usernames",name));if(!match.exists())return showStatus("No user has that exact username.",true);const target=match.data().uid,me=auth.currentUser.uid;if(target===me)return showStatus("You cannot add yourself.",true);if((await getDoc(doc(db,"blocks",`${me}_${target}`))).exists()||(await getDoc(doc(db,"blocks",`${target}_${me}`))).exists())return showStatus("This friend request cannot be sent.",true);if((await getDoc(doc(db,"friendships",pairId(me,target)))).exists())return showStatus("You are already friends.");const outgoing=await getDoc(doc(db,"friendRequests",`${me}_${target}`));if(outgoing.exists()&&outgoing.data().status==="pending"){f.reset();return showStatus(`A friend request is already waiting for ${match.data().username}.`)}const incoming=await getDoc(doc(db,"friendRequests",`${target}_${me}`));if(incoming.exists()&&incoming.data().status==="pending"){f.reset();return showStatus(`${match.data().username} already sent you a request. Check Requests.`)}await setDoc(doc(db,"friendRequests",`${me}_${target}`),{fromUid:me,toUid:target,status:"pending",createdAt:serverTimestamp()});f.reset();showStatus(`Friend request sent to ${match.data().username}.`)}catch(err){showStatus(friendlyError(err),true)}};
async function markRead(id){try{await updateDoc(doc(db,"chats",id),new FieldPath("readAt",auth.currentUser.uid),serverTimestamp(),new FieldPath("unreadCounts",auth.currentUser.uid),0)}catch{}}
function updateChatSignals(){if(!activeFriend)return;const c=chats.get(pairId(auth.currentUser.uid,activeFriend.uid)),typing=c?.typing?.[activeFriend.uid];$("#typing-status").textContent=typing&&Date.now()-ms(typing)<6000?`${activeFriend.username} is typing…`:"";const receipts=[...document.querySelectorAll(".message.mine small")];receipts.forEach(x=>x.textContent=x.dataset.time||x.textContent);const last=receipts.at(-1);if(last&&ms(c?.readAt?.[activeFriend.uid])>=Number(last.dataset.sent||0))last.textContent=`${last.dataset.time} · Read`}
function openChat(f){activeGroup=null;activeFriend=f;setReply(null);showView("friends");showStatus();const d=friendProfiles.get(f.uid)||f;$("#chat-title").textContent=`${d.avatar||"🙂"} ${d.displayName||d.username}${badgeFor(d)?` ${badgeFor(d)}`:""}`;$("#pin-conversation").textContent=(profile?.pinnedFriends||[]).includes(f.uid)?"Unpin":"Pin";$("#chat-actions").hidden=false;document.querySelectorAll(".dm-action").forEach(x=>x.hidden=false);document.querySelectorAll(".group-action").forEach(x=>x.hidden=true);$("#message-form").hidden=false;const id=pairId(auth.currentUser.uid,f.uid);stopMessages();markRead(id);stopMessages=onSnapshot(query(collection(db,"chats",id,"messages"),orderBy("createdAt","asc"),limit(100)),snap=>{const list=$("#message-list");list.replaceChildren();if(snap.empty)list.append(Object.assign(document.createElement("p"),{textContent:"No messages yet. Say hi!"}));snap.forEach(x=>list.append(renderMessage(x,d.displayName||d.username)));list.scrollTop=list.scrollHeight;markRead(id);updateChatSignals();showStatus()},e=>showStatus(friendlyError(e),true))}
$("#message-form").onsubmit=async e=>{e.preventDefault();const field=e.currentTarget.elements.message,text=field.value.trim();if((!text&&!attachmentData)||text.length>500)return;const payload={senderId:auth.currentUser.uid,text,createdAt:serverTimestamp()};if(replyTo)payload.reply=replyTo;if(attachmentData)payload.attachment=attachmentData;try{if(activeFriend){const id=pairId(auth.currentUser.uid,activeFriend.uid),ref=doc(db,"chats",id),members=[auth.currentUser.uid,activeFriend.uid].sort(),message=addDoc(collection(db,"chats",id,"messages"),payload),summary=setDoc(ref,{members,updatedAt:serverTimestamp(),lastMessage:(text||"Image").slice(0,80),lastSenderId:auth.currentUser.uid,unreadCounts:{[activeFriend.uid]:increment(1)}},{merge:true});field.value="";$("#message-attachment").value="";attachmentData=null;setReply(null);await Promise.all([message,summary])}else if(activeGroup){const ref=doc(db,"groupChats",activeGroup.id),args=["updatedAt",serverTimestamp(),"lastMessage",(text||"Image").slice(0,80),"lastSenderId",auth.currentUser.uid];activeGroup.members.filter(uid=>uid!==auth.currentUser.uid).forEach(uid=>args.push(new FieldPath("unreadCounts",uid),increment(1)));const message=addDoc(collection(db,"groupChats",activeGroup.id,"messages"),{...payload,senderName:profile.displayName||profile.username}),summary=updateDoc(ref,...args);field.value="";$("#message-attachment").value="";attachmentData=null;setReply(null);await Promise.all([message,summary])}else return;showStatus()}catch(err){showStatus(friendlyError(err),true)}};
$("#message-form").elements.message.addEventListener("input",async()=>{if(!activeFriend)return;const ref=doc(db,"chats",pairId(auth.currentUser.uid,activeFriend.uid));await updateDoc(ref,new FieldPath("typing",auth.currentUser.uid),serverTimestamp()).catch(()=>{});clearTimeout(typingTimer);typingTimer=setTimeout(()=>updateDoc(ref,new FieldPath("typing",auth.currentUser.uid),null).catch(()=>{}),4500)});
$("#block-user").onclick=async()=>{if(!activeFriend||!confirm(`Block ${activeFriend.username}? You will no longer be friends.`))return;await setDoc(doc(db,"blocks",`${auth.currentUser.uid}_${activeFriend.uid}`),{blockerUid:auth.currentUser.uid,blockedUid:activeFriend.uid,createdAt:serverTimestamp()});await deleteDoc(doc(db,"friendships",pairId(auth.currentUser.uid,activeFriend.uid))).catch(()=>{});activeFriend=null;stopMessages();$("#chat-title").textContent="Select a friend";$("#chat-actions").hidden=true;$("#message-form").hidden=true;$("#message-list").textContent="User blocked."};
$("#remove-friend").onclick=async()=>{if(!activeFriend||!confirm(`Remove ${activeFriend.username} from your friends?`))return;await deleteDoc(doc(db,"friendships",pairId(auth.currentUser.uid,activeFriend.uid))).catch(err=>showStatus(friendlyError(err),true));activeFriend=null;stopMessages();$("#chat-title").textContent="Select a friend";$("#chat-actions").hidden=true;$("#message-form").hidden=true;$("#message-list").textContent="Friend removed.";showStatus("Friend removed.")};
$("#pin-conversation").onclick=async()=>{if(!activeFriend)return;const pins=[...(profile?.pinnedFriends||[])],index=pins.indexOf(activeFriend.uid);index>=0?pins.splice(index,1):pins.unshift(activeFriend.uid);await updateDoc(doc(db,"users",auth.currentUser.uid),{pinnedFriends:pins}).catch(err=>showStatus(friendlyError(err),true));$("#pin-conversation").textContent=index>=0?"Pin":"Unpin"};
$("#report-user").onclick=async()=>{if(!activeFriend)return;const reason=prompt(`Why are you reporting ${activeFriend.username}?`);if(!reason?.trim())return;await addDoc(collection(db,"reports"),{reporterUid:auth.currentUser.uid,reportedUid:activeFriend.uid,reason:reason.trim().slice(0,500),createdAt:serverTimestamp()});showStatus("Report sent. Thank you.")};
function showView(v){$(".social-layout").hidden=v!=="friends";$("#profile-editor").hidden=v!=="profile";$("#friend-profile-view").hidden=v!=="friend-profile";$("#group-manager-view").hidden=v!=="group-manager";$("#leaderboard-view").hidden=v!=="leaderboard";$("#account-settings-view").hidden=v!=="settings"}
document.querySelectorAll(".social-view-button").forEach(b=>b.onclick=()=>showView(b.dataset.socialView));
async function renderGroupManager(){if(!activeGroup)return;const owner=activeGroup.ownerUid===auth.currentUser.uid;$("#group-rename-form").hidden=!owner;$("#group-add-form").hidden=!owner;$("#group-rename-form").elements.name.value=activeGroup.name;const list=$("#group-member-list");list.replaceChildren();for(const uid of activeGroup.members){const user=await getDoc(doc(db,"users",uid)),name=user.data()?.displayName||user.data()?.username||"Unknown member",actions=[];if(owner&&uid!==activeGroup.ownerUid)actions.push(button("Remove",async()=>{if(!confirm(`Remove ${name} from this group?`))return;await updateDoc(doc(db,"groupChats",activeGroup.id),{members:activeGroup.members.filter(x=>x!==uid)}).catch(err=>showStatus(friendlyError(err),true))}));list.append(row(`${uid===activeGroup.ownerUid?"👑 ":""}${name}`,actions))}}
$("#group-manage").onclick=()=>{showView("group-manager");renderGroupManager()};$("#group-manager-back").onclick=()=>activeGroup&&openGroup(activeGroup);
$("#group-rename-form").onsubmit=async e=>{e.preventDefault();const name=String(new FormData(e.currentTarget).get("name")).trim();if(!name)return;await updateDoc(doc(db,"groupChats",activeGroup.id),{name,updatedAt:serverTimestamp()}).then(()=>showStatus("Group renamed.")).catch(err=>showStatus(friendlyError(err),true))};
$("#group-add-form").onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,username=String(new FormData(f).get("username")).trim().toLowerCase();try{if(activeGroup.members.length>=8)throw Error("Groups can have up to 8 members.");const match=await getDoc(doc(db,"usernames",username));if(!match.exists())throw Error("That username does not exist.");const uid=match.data().uid;if(activeGroup.members.includes(uid))throw Error("That person is already in the group.");if(!(await getDoc(doc(db,"friendships",pairId(auth.currentUser.uid,uid)))).exists())throw Error("You can only add your friends.");await updateDoc(doc(db,"groupChats",activeGroup.id),{members:[...activeGroup.members,uid],updatedAt:serverTimestamp()});f.reset();showStatus("Member added.")}catch(err){showStatus(friendlyError(err),true)}};
$("#group-leave").onclick=async()=>{if(!activeGroup)return;const owner=activeGroup.ownerUid===auth.currentUser.uid;if(!confirm(owner?"Delete this group for everyone?":"Leave this group?"))return;try{owner?await deleteDoc(doc(db,"groupChats",activeGroup.id)):await updateDoc(doc(db,"groupChats",activeGroup.id),{members:activeGroup.members.filter(uid=>uid!==auth.currentUser.uid)});activeGroup=null;stopMessages();$("#chat-title").textContent="Select a conversation";$("#chat-actions").hidden=true;$("#message-form").hidden=true;showStatus(owner?"Group deleted.":"You left the group.")}catch(err){showStatus(friendlyError(err),true)}};
$("#friend-profile-back").onclick=()=>showView("friends");
function showFriendProfile(uid,supplied){const d=supplied||friendProfiles.get(uid);if(!d)return;profileLinkUsername=d.username;const box=$("#friend-profile-content");box.replaceChildren();const avatar=document.createElement("span"),name=document.createElement("h3"),user=document.createElement("p"),statusText=document.createElement("p"),bio=document.createElement("p"),activityLine=document.createElement("p"),stats=document.createElement("p"),earned=badgeFor(d);avatar.className="profile-avatar";applyAvatar(avatar,d);name.textContent=`${d.displayName||d.username}${earned?` ${earned}`:""}`;user.textContent=`@${d.username}`;statusText.className="profile-status-text";statusText.textContent=d.statusText||"";bio.textContent=d.bio||"No bio yet.";activityLine.textContent=activity(d);stats.textContent=`${Math.floor((d.stats?.playSeconds||0)/60)} minutes played`;box.append(avatar,name,user,statusText,bio,activityLine,stats);showView("friend-profile")}
$("#copy-profile-link").onclick=async()=>{const url=new URL(location.href);url.search="";url.searchParams.set("user",profileLinkUsername);try{await navigator.clipboard.writeText(url.href);showStatus("Profile link copied.")}catch{showStatus(url.href)}};
async function openLinkedProfile(){const username=new URLSearchParams(location.search).get("user")?.trim().toLowerCase();if(!username||profileLinkOpened||!auth.currentUser)return;profileLinkOpened=true;try{const nameDoc=await getDoc(doc(db,"usernames",username));if(!nameDoc.exists())throw Error("That profile does not exist.");const userDoc=await getDoc(doc(db,"users",nameDoc.data().uid));if(!userDoc.exists())throw Error("That profile does not exist.");panel.hidden=false;showFriendProfile(nameDoc.data().uid,userDoc.data())}catch(err){showStatus(friendlyError(err),true)}}
$("#profile-form").elements.bio.oninput=e=>$("#bio-count").textContent=e.target.value.length;
$("#avatar-file").onchange=e=>{const file=e.target.files?.[0];if(!file)return;if(!["image/png","image/jpeg","image/webp"].includes(file.type)||file.size>5*1024*1024){e.target.value="";return showStatus("Choose a PNG, JPEG, or WebP under 5 MB.",true)}const reader=new FileReader();reader.onload=()=>{const image=new Image();image.onload=()=>{const canvas=document.createElement("canvas"),size=256,side=Math.min(image.width,image.height),sx=(image.width-side)/2,sy=(image.height-side)/2;canvas.width=canvas.height=size;canvas.getContext("2d").drawImage(image,sx,sy,side,side,0,0,size,size);pendingAvatarImage=canvas.toDataURL("image/webp",.72);if(pendingAvatarImage.length>150000)return showStatus("That picture could not be compressed enough. Try another image.",true);showStatus("Profile picture ready. Press Save profile.")};image.src=reader.result};reader.readAsDataURL(file)};
$("#profile-form").onsubmit=async e=>{e.preventDefault();const d=new FormData(e.currentTarget),displayName=String(d.get("displayName")).trim(),statusText=String(d.get("statusText")).trim(),bio=String(d.get("bio")).trim(),changes={displayName,statusText,bio},nameChanged=displayName!==(profile.displayName||profile.username);if(!displayName||displayName.length>30)return showStatus("Display name must be 1–30 characters.",true);if(nameChanged){const changed=ms(profile.displayNameChangedAt),wait=24*60*60*1000;if(changed&&Date.now()-changed<wait)return showStatus(`You can change your display name again in ${Math.ceil((wait-(Date.now()-changed))/3600000)} hours.`,true);changes.displayNameChangedAt=serverTimestamp()}if(pendingAvatarImage)changes.avatarImage=pendingAvatarImage;try{await updateDoc(doc(db,"users",auth.currentUser.uid),changes);pendingAvatarImage=null;$("#avatar-file").value="";showStatus("Profile saved.")}catch(err){showStatus(friendlyError(err),true)}};
document.addEventListener("simplegames:profile",e=>{const d=e.detail.profile;$("#profile-form").elements.statusText.value=d.statusText||"";$("#profile-avatar").textContent="";applyAvatar($("#profile-avatar"),d);openLinkedProfile()});
for(const [id,key]of[["#message-sound-setting","messageSound"],["#dnd-setting","doNotDisturb"],["#hide-online-setting","hideOnline"],["#private-activity-setting","privateActivity"]])$(id).onchange=e=>updateDoc(doc(db,"users",auth.currentUser.uid),{[key]:e.target.checked}).then(()=>showStatus("Account setting saved.")).catch(err=>showStatus(friendlyError(err),true));
$("#username-form").onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,username=String(new FormData(f).get("username")).trim(),lower=username.toLowerCase();if(!/^[A-Za-z0-9_]{3,20}$/.test(username))return showStatus("Username must be 3–20 letters, numbers, or underscores.",true);if(lower===profile.usernameLower)return showStatus("Choose a different username.",true);const changed=ms(profile?.usernameChangedAt),wait=30*24*60*60*1000;if(changed&&Date.now()-changed<wait)return showStatus(`You can change it again in ${Math.ceil((wait-(Date.now()-changed))/86400000)} days.`,true);try{await runTransaction(db,async t=>{const next=doc(db,"usernames",lower),taken=await t.get(next);if(taken.exists()&&taken.data().uid!==auth.currentUser.uid)throw Error("That username is already taken.");t.delete(doc(db,"usernames",profile.usernameLower));t.set(next,{uid:auth.currentUser.uid,username});t.update(doc(db,"users",auth.currentUser.uid),{username,usernameLower:lower,usernameChangedAt:serverTimestamp()})});f.reset();showStatus("Username changed.")}catch(err){showStatus(friendlyError(err),true)}};
function listenBlocks(uid){stopBlocks();stopBlocks=onSnapshot(query(collection(db,"blocks"),where("blockerUid","==",uid)),async snap=>{const list=$("#blocked-list");list.replaceChildren();if(snap.empty)return list.append(Object.assign(document.createElement("p"),{textContent:"No blocked users"}));for(const block of snap.docs){const u=await getDoc(doc(db,"users",block.data().blockedUid)),name=u.data()?.username||"Unknown user";list.append(row(name,[button("Unblock",async()=>{await deleteDoc(block.ref);showStatus(`${name} was unblocked.`)})]))}})}
function listenLeaderboard(){stopLeaderboard();stopLeaderboard=onSnapshot(query(collection(db,"users"),orderBy("stats.playSeconds","desc"),limit(25)),snap=>{const list=$("#leaderboard-list");list.replaceChildren();if(snap.empty)return list.append(Object.assign(document.createElement("li"),{textContent:"No playtime recorded yet."}));snap.forEach(entry=>{const d=entry.data(),item=document.createElement("li"),avatar=document.createElement("span"),name=document.createElement("strong"),time=document.createElement("span");avatar.className="profile-avatar";applyAvatar(avatar,d);name.textContent=d.displayName||d.username;time.textContent=`${Math.floor((d.stats?.playSeconds||0)/60)} min`;item.append(avatar,name,time);list.append(item)})},e=>showStatus(friendlyError(e),true))}
async function presence(extra={}){if(auth.currentUser)await updateDoc(doc(db,"users",auth.currentUser.uid),{status:document.visibilityState==="visible"?"online":"away",lastActive:serverTimestamp(),...extra}).catch(()=>{})}
document.addEventListener("visibilitychange",()=>presence());window.addEventListener("simplegames:play",e=>presence({currentGame:e.detail}));window.addEventListener("simplegames:stop-playing",()=>presence({currentGame:null}));
$("#sign-out").onclick=async()=>{await updateDoc(doc(db,"users",auth.currentUser.uid),{status:"offline",lastActive:serverTimestamp(),currentGame:null}).catch(()=>{});await signOut(auth)};
onAuthStateChanged(auth,user=>{stopProfile();stopRequests();stopFriends();stopChats();stopMessages();stopBlocks();stopFriendProfiles.forEach(s=>s());stopFriendProfiles=[];clearInterval(presenceTimer);activeFriend=null;friends=[];chats.clear();friendProfiles.clear();chatsReady=false;document.dispatchEvent(new CustomEvent("simplegames:auth",{detail:{user}}));if(!user){profile=null;authView.hidden=false;socialView.hidden=true;$("#account-open").childNodes[0].textContent="Log in";$("#account-unread").hidden=true;return}authView.hidden=true;socialView.hidden=false;showView("friends");$("#account-email").textContent=user.email||"";stopProfile=onSnapshot(doc(db,"users",user.uid),p=>{if(!p.exists())return;profile=p.data();const display=profile.displayName||profile.username,earned=badgeFor(profile);$("#profile-display-name").textContent=`${display}${earned?` ${earned}`:""}`;$("#profile-username").textContent=`@${profile.username}`;$("#profile-avatar").textContent=profile.avatar||"🙂";$("#account-open").childNodes[0].textContent=display;$("#message-sound-setting").checked=profile.messageSound!==false;$("#dnd-setting").checked=!!profile.doNotDisturb;$("#hide-online-setting").checked=!!profile.hideOnline;$("#private-activity-setting").checked=!!profile.privateActivity;const f=$("#profile-form");if(document.activeElement?.form!==f){f.elements.displayName.value=display;f.elements.avatar.value=profile.avatar||"🙂";f.elements.bio.value=profile.bio||"";$("#bio-count").textContent=(profile.bio||"").length}document.dispatchEvent(new CustomEvent("simplegames:profile",{detail:{user,profile}}))});listenRequests(user.uid);listenFriends(user.uid);listenChats(user.uid);listenBlocks(user.uid);presence();presenceTimer=setInterval(()=>presence(),120000)});
onAuthStateChanged(auth,user=>{stopGroups();activeGroup=null;groups.clear();groupsReady=false;if(user)listenGroups(user.uid)});
onAuthStateChanged(auth,user=>{stopLeaderboard();if(user)listenLeaderboard()});
const renderFriendsBase=renderFriends;renderFriends=()=>{renderFriendsBase();updateAccountUnread()};
const openChatBase=openChat;openChat=f=>{const d=friendProfiles.get(f.uid);if(d)friendProfiles.set(f.uid,{...d,avatar:""});openChatBase(f);const shown=friendProfiles.get(f.uid)||f;$("#chat-title").textContent=shown.displayName||shown.username};
if(new URLSearchParams(location.search).has("user")){panel.hidden=false;showStatus("Log in to view this profile.")}
