import {getApp} from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js';
import {getAuth,onAuthStateChanged} from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js';
import {collection,doc,getDoc,getDocs,getFirestore,limit,onSnapshot,orderBy,query,serverTimestamp,setDoc,deleteDoc,updateDoc,where,writeBatch} from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js';
import {findUser} from './user-lookup.js?v=1';
import {categories,ticketHints,validTicket,staffRole} from './support-model.js?v=2';
const auth=getAuth(getApp()),db=getFirestore(getApp()),$=s=>document.querySelector(s);
const panel=document.createElement('section');panel.id='support-panel';panel.className='support-panel';panel.hidden=true;panel.setAttribute('aria-label','Support');
panel.innerHTML=`<header class="support-heading"><button id="support-home" type="button">← Home</button><h1>Support</h1><button id="support-close" type="button" aria-label="Close support">×</button></header>
<nav class="support-nav" aria-label="Support views"><button type="button" data-support-view="new" aria-pressed="true">Open a Ticket</button><button type="button" data-support-view="mine" aria-pressed="false">My Tickets</button><button type="button" data-support-view="staff" hidden>Staff Inbox</button><button type="button" data-support-view="team" hidden>Manage Staff</button></nav>
<p id="support-status" class="support-status" role="status"></p><div id="support-login" class="support-box" hidden><h2>Log in to get help</h2><p class="support-muted">Your tickets are private between you and the support team.</p><button id="support-login-button" type="button">Log in</button></div>
<form id="support-new" class="support-box"><h2>What do you need help with?</h2><p class="support-muted">Open a ticket and staff will reply here. Screenshots are optional, but helps us understand better.</p><div class="support-categories" id="support-categories"></div><label>Subject<input name="subject" placeholder="A quick summary…" minlength="3" maxlength="100" required /></label><label>Description<textarea name="description" minlength="10" maxlength="3000" placeholder="Tell us what happened, or which game you would like added…" required></textarea></label><label>Screenshot · Optional<input id="support-image" type="file" accept="image/png,image/jpeg,image/webp" /><small class="support-muted">PNG, JPG or WebP · up to 8 MB. Resized before sending. Please hide private information.</small></label><img id="support-image-preview" class="support-screenshot" alt="Screenshot preview" hidden /><button id="support-image-remove" type="button" hidden>Remove screenshot</button><button class="support-primary" type="submit">Open Ticket</button></form>
<section id="support-list" class="support-box" hidden><h2 id="support-list-title">My Tickets</h2><label>Search tickets<input id="support-search" type="search" placeholder="Search subject or category…" /></label><div id="support-ticket-list"></div></section>
<section id="support-detail" class="support-box" hidden><button id="support-back" type="button">← Back to Tickets</button><div class="support-ticket-heading"><h2 id="support-ticket-title"></h2><button id="support-ticket-state" type="button" hidden></button></div><p id="support-ticket-meta" class="support-muted"></p><div id="support-ticket-description" class="support-ticket-body"></div><img id="support-ticket-image" class="support-screenshot" alt="Attached screenshot" hidden /><h3>Replies</h3><div id="support-replies"></div><form id="support-reply-form"><label>Your reply<textarea name="message" minlength="1" maxlength="2000" required></textarea></label><button type="submit" class="support-primary">Send Reply</button></form></section>
<section id="support-team" class="support-box" hidden><h2>Manage Staff</h2><p class="support-muted">All staff can read, reply to, and close every ticket. Only the owner can grant or remove access.</p><form id="support-staff-form"><label>Exact username<input name="username" required placeholder="username" /></label><label>Role<select name="role"><option value="support">Support</option><option value="admin">Admin</option></select></label><button type="submit">Give Staff Access</button></form><div id="support-staff-list"></div></section>`;
document.body.append(panel);
let user=auth.currentUser,owner=false,staff=false,category=categories[0],screen='',imageBusy=false,view='new',tickets=[],active=null,stops=[],generation=0;
const say=text=>$('#support-status').textContent=text;
const errorText=e=>e.code==='permission-denied'?'Support access is not set up yet, or you no longer have permission.':e.code==='resource-exhausted'?'Firebase has reached its usage limit. Try again later.':'Could not load or save support data. Please try again.';
function stop(){stops.forEach(fn=>fn());stops=[];generation++}
function close(){panel.hidden=true;stop();screen='';$('#support-new').reset();$('#support-image-preview').hidden=true;$('#support-image-remove').hidden=true}
$('#support-close').onclick=close;$('#support-home').onclick=()=>{close();$('.brand')?.click()};
$('#support-login-button').onclick=()=>{close();$('#account-open').click()};
function updateTicketHints(){const form=$('#support-new'),hints=ticketHints[category];form.elements.subject.placeholder=hints.subject;form.elements.description.placeholder=hints.description}
for(const name of categories){const b=document.createElement('button');b.type='button';b.textContent=name;b.setAttribute('aria-pressed',String(name===category));b.onclick=()=>{category=name;updateTicketHints();$('#support-categories').querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)))};$('#support-categories').append(b)}
updateTicketHints();
function renderList(){const list=$('#support-ticket-list'),term=$('#support-search').value.toLowerCase();list.replaceChildren();const shown=tickets.filter(t=>(t.subject+' '+t.category).toLowerCase().includes(term)).sort((a,b)=>(b.updatedAt?.toMillis?.()||0)-(a.updatedAt?.toMillis?.()||0));if(!shown.length){list.textContent='No tickets found.';return}for(const ticket of shown){const b=document.createElement('button');b.type='button';b.className='support-ticket-row';const copy=document.createElement('span'),title=document.createElement('strong'),meta=document.createElement('small'),state=document.createElement('small');title.textContent=ticket.subject;meta.textContent=ticket.category+' · '+ticket.ownerName;state.textContent=ticket.status==='closed'?'Closed':'Open';copy.append(title,meta);b.append(copy,state);b.onclick=()=>openTicket(ticket.id);list.append(b)}}
$('#support-search').oninput=renderList;
async function show(next){stop();view=next;say('');active=null;for(const id of ['new','list','detail','team'])$('#support-'+id).hidden=true;$('#support-login').hidden=!!user;panel.querySelectorAll('[data-support-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.supportView===next)));if(!user)return;
 if(next==='new'){$('#support-new').hidden=false;return}
 if(next==='team'){if(!owner)return;$('#support-team').hidden=false;const version=generation;try{const snap=await getDocs(query(collection(db,'supportStaff'),limit(100)));if(version!==generation)return;const list=$('#support-staff-list');list.replaceChildren();for(const item of snap.docs){const row=document.createElement('div');row.className='support-staff-row';const name=document.createElement('span'),remove=document.createElement('button');name.textContent=(item.data().username||item.id)+' · '+item.data().role;remove.type='button';remove.textContent='Remove Access';remove.onclick=async()=>{try{await deleteDoc(item.ref);await show('team')}catch(e){say(errorText(e))}};row.append(name,remove);list.append(row)}}catch(e){say(errorText(e))}return}
 if(next==='staff'&&!staff)return;$('#support-list').hidden=false;$('#support-list-title').textContent=next==='staff'?'Staff Inbox':'My Tickets';tickets=[];$('#support-ticket-list').textContent='Loading…';const q=next==='staff'?query(collection(db,'supportTickets'),limit(100)):query(collection(db,'supportTickets'),where('ownerUid','==',user.uid),limit(100));const version=generation;stops.push(onSnapshot(q,snap=>{if(version!==generation)return;tickets=snap.docs.map(d=>({id:d.id,...d.data()}));renderList()},e=>{if(version===generation)say(errorText(e))}));
}
async function open(){panel.hidden=false;stop();const version=generation;owner=staff=false;panel.querySelector('[data-support-view="staff"]').hidden=true;panel.querySelector('[data-support-view="team"]').hidden=true;if(user){try{const [config,role]=await Promise.all([getDoc(doc(db,'supportSettings','access')),getDoc(doc(db,'supportStaff',user.uid))]);if(version!==generation)return;owner=config.exists()&&config.data().ownerUid===user.uid;staff=owner||(role.exists()&&staffRole(role.data().role));panel.querySelector('[data-support-view="staff"]').hidden=!staff;panel.querySelector('[data-support-view="team"]').hidden=!owner}catch(e){if(version!==generation)return;await show('new');say(errorText(e));return}}await show('new')}
document.addEventListener('click',event=>{if(event.target.closest('#support-open')){event.preventDefault();open()}});
panel.querySelector('.support-nav').onclick=event=>{const b=event.target.closest('[data-support-view]');if(b)show(b.dataset.supportView)};
onAuthStateChanged(auth,next=>{user=next;stop();owner=staff=false;tickets=[];active=null;$('#support-replies').replaceChildren();$('#support-ticket-description').textContent='';$('#support-ticket-image').removeAttribute('src');if(!panel.hidden)open()});
$('#support-image-remove').onclick=()=>{screen='';$('#support-image').value='';$('#support-image-preview').removeAttribute('src');$('#support-image-preview').hidden=true;$('#support-image-remove').hidden=true};
$('#support-image').onchange=async event=>{screen='';const file=event.target.files?.[0];if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>8*1024*1024){say('Choose a PNG, JPG or WebP under 8 MB.');event.target.value='';return}imageBusy=true;const version=generation;try{const bitmap=await createImageBitmap(file),canvas=document.createElement('canvas'),scale=Math.min(1,1000/Math.max(bitmap.width,bitmap.height));canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();let quality=.8,data=canvas.toDataURL('image/jpeg',quality);while(data.length>180000&&quality>.25){quality-=.1;data=canvas.toDataURL('image/jpeg',quality)}if(data.length>180000)throw Error('large');if(version!==generation)return;screen=data;$('#support-image-preview').src=screen;$('#support-image-preview').hidden=false;$('#support-image-remove').hidden=false;say('Screenshot ready.')}catch{say('Could not prepare that screenshot. Try a smaller image.')}finally{imageBusy=false}};
$('#support-new').onsubmit=async event=>{event.preventDefault();if(!user)return say('Log in first.');if(imageBusy)return say('Wait for the screenshot to finish.');const form=event.currentTarget,submit=form.querySelector('[type=submit]'),uid=user.uid,data={category,subject:form.elements.subject.value.trim(),description:form.elements.description.value.trim()};if(!validTicket(data))return say('Add a subject and at least 10 characters of detail.');submit.disabled=true;try{const profile=await getDoc(doc(db,'users',uid));if(user?.uid!==uid)return;const ref=doc(collection(db,'supportTickets')),batch=writeBatch(db);batch.set(ref,{...data,ownerUid:uid,ownerName:profile.data()?.username||'Member',status:'open',createdAt:serverTimestamp(),updatedAt:serverTimestamp()});if(screen)batch.set(doc(db,'supportTickets',ref.id,'attachments','screenshot'),{dataUrl:screen});await batch.commit();form.reset();screen='';$('#support-image-preview').hidden=true;$('#support-image-remove').hidden=true;await openTicket(ref.id);say('Ticket opened. Staff will reply here.')}catch(e){say(errorText(e))}finally{submit.disabled=false}};
async function openTicket(id){const back=view==='staff'?'staff':'mine';stop();const version=generation;for(const key of ['new','list','team'])$('#support-'+key).hidden=true;$('#support-detail').hidden=false;$('#support-ticket-description').textContent='Loading…';$('#support-ticket-title').textContent='Ticket';$('#support-ticket-image').hidden=true;$('#support-replies').replaceChildren();$('#support-reply-form').hidden=true;$('#support-ticket-state').hidden=true;$('#support-back').onclick=()=>show(back);
 stops.push(onSnapshot(doc(db,'supportTickets',id),snapshot=>{if(version!==generation)return;if(!snapshot.exists()){say('Ticket unavailable.');return}active={id,...snapshot.data()};$('#support-ticket-title').textContent=active.subject;$('#support-ticket-description').textContent=active.description;$('#support-ticket-meta').textContent=active.category+' · '+active.ownerName+' · '+active.status;$('#support-ticket-state').hidden=!staff;$('#support-ticket-state').textContent=active.status==='closed'?'Reopen Ticket':'Close Ticket';$('#support-reply-form').hidden=active.status==='closed'},e=>{if(version===generation){active=null;$('#support-detail').hidden=true;say(errorText(e))}}));
 stops.push(onSnapshot(query(collection(db,'supportTickets',id,'messages'),orderBy('createdAt','desc'),limit(100)),snap=>{if(version!==generation)return;const list=$('#support-replies');list.replaceChildren();if(snap.empty)list.textContent='No replies yet.';for(const item of [...snap.docs].reverse()){const data=item.data(),row=document.createElement('div'),meta=document.createElement('small'),body=document.createElement('div');row.className='support-message';meta.textContent=(data.staff?'Staff · ':'')+data.senderName+' · '+(data.createdAt?.toDate?.().toLocaleString()||'Sending…');body.textContent=data.text;row.append(meta,body);list.append(row)}},e=>{if(version===generation)say(errorText(e))}));
 try{const screenshot=await getDoc(doc(db,'supportTickets',id,'attachments','screenshot'));if(version===generation&&screenshot.exists()){$('#support-ticket-image').src=screenshot.data().dataUrl;$('#support-ticket-image').hidden=false}}catch(e){if(version===generation)say(errorText(e))}
}
$('#support-ticket-state').onclick=async()=>{if(!staff||!active)return;try{await updateDoc(doc(db,'supportTickets',active.id),{status:active.status==='closed'?'open':'closed',updatedAt:serverTimestamp()})}catch(e){say(errorText(e))}};
$('#support-reply-form').onsubmit=async event=>{event.preventDefault();if(!user||!active||active.status==='closed')return;const form=event.currentTarget,text=form.elements.message.value.trim(),submit=form.querySelector('button');if(!text)return;submit.disabled=true;const uid=user.uid,id=active.id;try{const profile=await getDoc(doc(db,'users',uid));if(user?.uid!==uid)return;const batch=writeBatch(db);batch.set(doc(collection(db,'supportTickets',id,'messages')),{senderUid:uid,senderName:profile.data()?.username||'Member',staff,text,createdAt:serverTimestamp()});batch.update(doc(db,'supportTickets',id),{updatedAt:serverTimestamp()});await batch.commit();form.reset();say('Reply sent.')}catch(e){say(errorText(e))}finally{submit.disabled=false}};
$('#support-staff-form').onsubmit=async event=>{event.preventDefault();if(!owner)return;const form=event.currentTarget,submit=form.querySelector('button');submit.disabled=true;try{const found=await findUser(db,form.elements.username.value);if(!found)throw Error('missing');const config=await getDoc(doc(db,'supportSettings','access'));if(found.uid===config.data()?.ownerUid){say('That account is already the owner.');return}await setDoc(doc(db,'supportStaff',found.uid),{role:form.elements.role.value,username:found.username,grantedBy:user.uid,grantedAt:serverTimestamp()});form.reset();await show('team');say('Staff access granted.')}catch(e){say(e.message==='missing'?'Username not found.':errorText(e))}finally{submit.disabled=false}};
new MutationObserver(()=>{if(panel.hidden)stop()}).observe(panel,{attributes:true,attributeFilter:['hidden']});
