import {getApp} from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js';
import {getAuth,onAuthStateChanged} from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js';
import {getFirestore,collection,doc,getDoc,addDoc,updateDoc,onSnapshot,query,where,arrayUnion,Timestamp} from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js';
const auth=getAuth(getApp()),db=getFirestore(getApp()),endpoint='https://simple-games-voice.maylarpp.workers.dev/token';
let context=null,current=null,room=null,busy=false,stopIncoming=()=>{},stopCall=()=>{},muted=true,deaf=false;
const dock=document.createElement('section');dock.className='voice-dock';dock.hidden=true;dock.setAttribute('aria-label','Voice call');
const heading=document.createElement('strong'),status=document.createElement('p'),people=document.createElement('div'),audio=document.createElement('div');status.setAttribute('role','status');
function button(label,action){const b=document.createElement('button');b.type='button';b.className='secondary-button';b.textContent=label;b.onclick=()=>Promise.resolve(action()).catch(error=>status.textContent=error.message);return b;}
const mic=button('Unmute',async()=>{if(!room)return;const next=!muted;await room.localParticipant.setMicrophoneEnabled(!next);muted=next;mic.textContent=muted?'Unmute':'Mute';});
const ears=button('Deafen',async()=>{deaf=!deaf;audio.querySelectorAll('audio').forEach(el=>el.muted=deaf);ears.textContent=deaf?'Undeafen':'Deafen';if(deaf&&!muted){await room?.localParticipant.setMicrophoneEnabled(false);muted=true;mic.textContent='Unmute';}});
const play=button('Enable audio',()=>room?.startAudio()),leave=button('Leave call',()=>disconnect());dock.append(heading,status,people,mic,ears,play,leave,audio);document.body.append(dock);
const invites=document.createElement('section');invites.className='voice-incoming';invites.setAttribute('aria-label','Incoming calls');document.body.append(invites);
const toggle=document.createElement('label'),setting=document.createElement('input');setting.type='checkbox';setting.checked=localStorage.getItem('sg-incoming-calls')!=='off';toggle.append(setting,' Allow incoming calls');document.querySelector('#account-settings-view')?.append(toggle);setting.onchange=()=>{localStorage.setItem('sg-incoming-calls',setting.checked?'on':'off');if(!setting.checked)invites.replaceChildren();};
const callButton=button('☎ Call',()=>startCall());document.querySelector('#chat-actions')?.prepend(callButton);
document.addEventListener('simplegames:voice-conversation',e=>context=e.detail);
function participants(){if(!room)return;people.replaceChildren();for(const p of [room.localParticipant,...room.remoteParticipants.values()]){const name=document.createElement('span');name.className='voice-person';name.classList.toggle('speaking',p.isSpeaking);name.textContent=p.identity===auth.currentUser?.uid?'You':p.identity.slice(0,6);people.append(name);getDoc(doc(db,'users',p.identity)).then(s=>{if(name.isConnected)name.textContent=p.identity===auth.currentUser?.uid?'You':s.data()?.displayName||s.data()?.username||'Member';}).catch(()=>{});}}
async function disconnect(){const old=current;current=null;stopCall();stopCall=()=>{};const oldRoom=room;room=null;await oldRoom?.disconnect();audio.replaceChildren();dock.hidden=true;busy=false;if(old?.callId&&auth.currentUser){try{await updateDoc(doc(db,'voiceCalls',old.callId),old.creatorUid===auth.currentUser.uid?{status:'ended'}:{declined:arrayUnion(auth.currentUser.uid)});}catch{}}}
async function connect(target){if(busy)throw Error('A call is already connecting.');if(current)throw Error('Leave your current call first.');if(!auth.currentUser)throw Error('Sign in first.');busy=true;dock.hidden=false;heading.textContent=target.label||'Voice call';status.textContent='Connecting…';mic.disabled=true;
  try{const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+await auth.currentUser.getIdToken()},body:JSON.stringify(target),signal:AbortSignal.timeout(20000)});const grant=await response.json();if(!response.ok)throw Error(grant.error||'Call connection denied.');const {Room,RoomEvent,Track}=await import('https://esm.sh/livekit-client@2.22.3');room=new Room();const selected=room;current=target;
    room.on(RoomEvent.TrackSubscribed,track=>{if(track.kind!==Track.Kind.Audio)return;const element=track.attach();element.muted=deaf;audio.append(element);});room.on(RoomEvent.TrackUnsubscribed,track=>track.detach().forEach(el=>el.remove()));
    for(const event of [RoomEvent.ParticipantConnected,RoomEvent.ParticipantDisconnected,RoomEvent.ActiveSpeakersChanged])room.on(event,participants);
    room.on(RoomEvent.Disconnected,()=>{if(room===selected){current=null;room=null;stopCall();audio.replaceChildren();status.textContent='Call disconnected. You can leave and try again.';mic.disabled=true;}});
    await room.connect(grant.server_url,grant.participant_token);muted=true;deaf=false;mic.textContent='Unmute';ears.textContent='Deafen';mic.disabled=room.localParticipant.permissions?.canPublish===false;status.textContent=mic.disabled?'Connected · listening only':'Connected · microphone starts muted';participants();
    if(target.callId)stopCall=onSnapshot(doc(db,'voiceCalls',target.callId),snapshot=>{const data=snapshot.data();if(!data||data.status==='ended'||data.declined?.includes(auth.currentUser?.uid)||Date.now()>=data.expiresAt?.toMillis()){void disconnect();return;}const other=data.members.filter(uid=>uid!==auth.currentUser?.uid);if(other.every(uid=>data.declined?.includes(uid)))void disconnect();},error=>{status.textContent=error.message;void disconnect();});
  }catch(error){const failed=room;room=null;current=null;await failed?.disconnect();status.textContent=error.name==='NotAllowedError'?'Microphone permission denied.':error.message;throw error;}finally{busy=false;}
}
async function startCall(){if(!context||!auth.currentUser)throw Error('Open a friend or group first.');dock.hidden=false;status.textContent='Starting call…';if(current||busy)throw Error('Leave your current call first.');const me=auth.currentUser.uid,source=await getDoc(doc(db,context.kind==='dm'?'friendships':'groupChats',context.id)),members=source.data()?.members||[];if(!members.includes(me))throw Error('Conversation unavailable.');const created=await addDoc(collection(db,'voiceCalls'),{kind:context.kind,conversationId:context.id,creatorUid:me,members,accepted:[me],declined:[],status:'active',createdAt:Timestamp.now(),expiresAt:Timestamp.fromMillis(Date.now()+2*60*60*1000),ringUntil:Timestamp.fromMillis(Date.now()+60000)});try{await connect({...context,callId:created.id,creatorUid:me});}catch(error){await updateDoc(created,{status:'ended'}).catch(()=>{});throw error;}}
onAuthStateChanged(auth,user=>{stopIncoming();invites.replaceChildren();void disconnect();if(!user)return;const shown=new Set();stopIncoming=onSnapshot(query(collection(db,'voiceCalls'),where('members','array-contains',user.uid)),snapshot=>{for(const element of [...invites.children]){const call=snapshot.docs.find(x=>x.id===element.dataset.id)?.data();if(!call||call.status!=='active'||call.accepted.includes(user.uid)||call.declined.includes(user.uid)||call.ringUntil.toMillis()<Date.now())element.remove();}for(const entry of snapshot.docs){const data=entry.data();if(!setting.checked||data.creatorUid===user.uid||data.status!=='active'||data.accepted.includes(user.uid)||data.declined.includes(user.uid)||data.ringUntil.toMillis()<Date.now()||shown.has(entry.id))continue;shown.add(entry.id);const card=document.createElement('article');card.dataset.id=entry.id;const title=document.createElement('strong');title.textContent='Incoming '+(data.kind==='group'?'group call':'call');getDoc(doc(db,'users',data.creatorUid)).then(s=>title.textContent=(s.data()?.displayName||s.data()?.username||'Friend')+' is calling').catch(()=>{});card.append(title,button('Accept',async()=>{if(current||busy)throw Error('Leave your current call first.');await updateDoc(entry.ref,{accepted:arrayUnion(user.uid)});card.remove();await connect({kind:data.kind,callId:entry.id,creatorUid:data.creatorUid,label:title.textContent});}),button('Decline',async()=>{await updateDoc(entry.ref,{declined:arrayUnion(user.uid)});card.remove();}));invites.append(card);setTimeout(()=>card.remove(),Math.max(0,data.ringUntil.toMillis()-Date.now()));document.dispatchEvent(new CustomEvent('simplegames:notification',{detail:{name:'Incoming call',text:title.textContent,sound:true,reply:undefined}}));}},()=>{});});
document.addEventListener('simplegames:voice-server',e=>{dock.hidden=false;connect({...e.detail,kind:'server'}).catch(error=>status.textContent=error.message);});
window.addEventListener('pagehide',()=>{room?.disconnect();});
